"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { BackHome, Panel } from "@/components/ui";
import { supabaseBrowser } from "@/lib/supabase/client";
import { currentWorkspace,peekWorkspaceContext } from "@/lib/supabase/workspace";
import { useRealtimeRefresh } from "@/lib/use-realtime-refresh";
import { todayInTZ } from "@/lib/timezone";

type Member={id:string;name:string;relation:string|null};
type FamilyTask={id:string;title:string;due_date:string|null;responsible:string|null;status:string;member_id:string|null;reminder_days:number|null};
type BabyRecord={id:string;date:string;type:string|null;title:string;value:string|null;notes:string|null};

export default function FamilyPage(){
  const cachedWorkspace=peekWorkspaceContext();const[workspaceId,setWorkspaceId]=useState(cachedWorkspace?.workspaceId||"");const[userId,setUserId]=useState(cachedWorkspace?.user.id||"");
  const[members,setMembers]=useState<Member[]>([]);const[tasks,setTasks]=useState<FamilyTask[]>([]);const[baby,setBaby]=useState<BabyRecord[]>([]);
  const[error,setError]=useState("");const[memberName,setMemberName]=useState("");const[relation,setRelation]=useState("Family");
  const[taskTitle,setTaskTitle]=useState("");const[memberId,setMemberId]=useState("");const[due,setDue]=useState(todayInTZ());const[responsible,setResponsible]=useState("Me");const[reminderDays,setReminderDays]=useState(2);
  const[babyTitle,setBabyTitle]=useState("");const[babyType,setBabyType]=useState("Milestone");const[babyDate,setBabyDate]=useState(todayInTZ());const[babyValue,setBabyValue]=useState("");const[babyNotes,setBabyNotes]=useState("");

  const load=useCallback(async()=>{try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx){setWorkspaceId("");return;}setWorkspaceId(ctx.workspaceId);setUserId(ctx.user.id);
    const[m,t,b]=await Promise.all([
      sb.from("family_members").select("id,name,relation").eq("workspace_id",ctx.workspaceId).order("created_at"),
      sb.from("family_tasks").select("id,title,due_date,responsible,status,member_id,reminder_days").eq("workspace_id",ctx.workspaceId).order("due_date",{ascending:true,nullsFirst:false}),
      sb.from("baby_records").select("id,date,type,title,value,notes").eq("workspace_id",ctx.workspaceId).order("date",{ascending:false}).limit(30)
    ]);if(m.error)throw m.error;if(t.error)throw t.error;if(b.error)throw b.error;setMembers((m.data||[]) as Member[]);setTasks((t.data||[]) as FamilyTask[]);setBaby((b.data||[]) as BabyRecord[]);
  }catch(e){setError(e instanceof Error?e.message:"Could not load family data");}},[]);
  useEffect(()=>{void load();},[load]);useRealtimeRefresh(["family_members","family_tasks","baby_records"],load,Boolean(workspaceId));

  async function addMember(e:FormEvent){e.preventDefault();if(!workspaceId||!memberName.trim())return;const sb=supabaseBrowser();const{error:x}=await sb.from("family_members").insert({workspace_id:workspaceId,created_by:userId,name:memberName.trim(),relation});if(x)setError(x.message);else{setMemberName("");await load();}}
  async function addTask(e:FormEvent){e.preventDefault();if(!workspaceId||!taskTitle.trim())return;const sb=supabaseBrowser();const{error:x}=await sb.from("family_tasks").insert({workspace_id:workspaceId,created_by:userId,title:taskTitle.trim(),member_id:memberId||null,due_date:due||null,responsible:responsible.trim()||"Me",reminder_days:reminderDays,status:"Pending"});if(x)setError(x.message);else{setTaskTitle("");setResponsible("Me");setReminderDays(2);await load();}}
  async function toggle(t:FamilyTask){const sb=supabaseBrowser();const{error:x}=await sb.from("family_tasks").update({status:t.status==="Completed"?"Pending":"Completed",updated_at:new Date().toISOString()}).eq("id",t.id);if(x)setError(x.message);else await load();}
  async function addBaby(e:FormEvent){e.preventDefault();if(!workspaceId||!babyTitle.trim())return;const sb=supabaseBrowser();const{error:x}=await sb.from("baby_records").insert({workspace_id:workspaceId,created_by:userId,date:babyDate||todayInTZ(),type:babyType,title:babyTitle.trim(),value:babyValue.trim()||null,notes:babyNotes.trim()||null});if(x)setError(x.message);else{setBabyTitle("");setBabyValue("");setBabyNotes("");setBabyDate(todayInTZ());await load();}}
  async function editMember(m:Member){const name=prompt("Name",m.name);if(!name?.trim())return;const relation=prompt("Relation",m.relation||"Family");if(relation==null)return;const sb=supabaseBrowser();const{error:x}=await sb.from("family_members").update({name:name.trim(),relation:relation.trim()||"Family"}).eq("id",m.id);if(x)setError(x.message);else await load();}
  async function removeMember(m:Member){if((m.relation||"").toLowerCase()==="me"){setError("Your own family profile cannot be deleted.");return;}if(!confirm(`Delete family member "${m.name}"? Existing tasks stay but become unlinked.`))return;const sb=supabaseBrowser();const{error:x}=await sb.from("family_members").delete().eq("id",m.id);if(x)setError(x.message);else await load();}
  async function editTask(t:FamilyTask){const title=prompt("Task",t.title);if(!title?.trim())return;const due=prompt("Due date (YYYY-MM-DD)",t.due_date||"");if(due==null)return;const responsible=prompt("Responsible",t.responsible||"Me");if(responsible==null)return;const reminder=prompt("Reminder days before due date",String(t.reminder_days??2));if(reminder==null)return;const reminderDays=Math.max(0,Math.min(90,Number(reminder)||0));const sb=supabaseBrowser();const{error:x}=await sb.from("family_tasks").update({title:title.trim(),due_date:due||null,responsible:responsible.trim()||"Me",reminder_days:reminderDays,updated_at:new Date().toISOString()}).eq("id",t.id);if(x)setError(x.message);else await load();}
  async function removeTask(t:FamilyTask){if(!confirm(`Delete family task "${t.title}"?`))return;const sb=supabaseBrowser();const{error:x}=await sb.from("family_tasks").delete().eq("id",t.id);if(x)setError(x.message);else await load();}
  async function editBaby(r:BabyRecord){const title=prompt("Record title",r.title);if(!title?.trim())return;const value=prompt("Value / detail",r.value||"");if(value==null)return;const notes=prompt("Notes",r.notes||"");if(notes==null)return;const date=prompt("Date (YYYY-MM-DD)",r.date);if(!date)return;const sb=supabaseBrowser();const q=await sb.from("baby_records").update({title:title.trim(),value:value.trim()||null,notes:notes.trim()||null,date}).eq("id",r.id);if(q.error)setError(q.error.message);else await load();}
  async function removeBaby(r:BabyRecord){if(!confirm(`Delete baby record "${r.title}"?`))return;const sb=supabaseBrowser();const{error:x}=await sb.from("baby_records").delete().eq("id",r.id);if(x)setError(x.message);else await load();}

  return <main className="pt-6"><BackHome/><p className="mt-2 text-[11px] tracking-widest text-slate-400">FAMILY OS</p><h1 className="text-2xl font-bold">Shared responsibilities</h1>
    {error&&<p className="mt-3 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}
    {!workspaceId?<p className="panel mt-4 p-5 text-sm">Sign in to use Family OS. <Link href="/login" className="text-[#8ab6ff]">Login →</Link></p>:
    <div className="mt-4 grid gap-4 md:grid-cols-2">
      <Panel title="Family members"><form onSubmit={addMember} className="flex gap-2"><input required value={memberName} onChange={e=>setMemberName(e.target.value)} placeholder="Name" className="min-w-0 flex-1 rounded-lg border border-white/10 bg-[#0a1524] p-2"/><input value={relation} onChange={e=>setRelation(e.target.value)} placeholder="Relation" className="w-32 rounded-lg border border-white/10 bg-[#0a1524] p-2"/><button className="rounded-lg border border-white/10 px-3">Add</button></form>
        <div className="mt-3 flex flex-wrap gap-2">{members.map(m=><span key={m.id} className="inline-flex items-center gap-2 rounded-full border border-white/10 px-3 py-1 text-xs">{m.name} · {m.relation||"Family"}<button type="button" onClick={()=>editMember(m)} className="text-[#8ab6ff]">Edit</button>{(m.relation||"").toLowerCase()!=="me"&&<button type="button" onClick={()=>removeMember(m)} className="text-red-300">Delete</button>}</span>)}</div>
      </Panel>
      <Panel title="Add family task"><form onSubmit={addTask} className="space-y-2"><input required value={taskTitle} onChange={e=>setTaskTitle(e.target.value)} placeholder="Task" className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><div className="grid grid-cols-2 gap-2"><select value={memberId} onChange={e=>setMemberId(e.target.value)} className="rounded-lg border border-white/10 bg-[#0a1524] p-2"><option value="">General family</option>{members.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><input type="date" value={due} onChange={e=>setDue(e.target.value)} className="rounded-lg border border-white/10 bg-[#0a1524] p-2"/></div><div className="grid grid-cols-2 gap-2"><input value={responsible} onChange={e=>setResponsible(e.target.value)} placeholder="Responsible e.g. Me + Wife"/><label className="text-xs text-slate-400">Reminder days before<input type="number" min="0" max="90" value={reminderDays} onChange={e=>setReminderDays(Math.max(0,Math.min(90,Number(e.target.value)||0)))} className="mt-1 w-full"/></label></div><button className="w-full rounded-lg bg-[#77adff] p-2 font-bold text-[#06101f]">Save task</button></form></Panel>
      <Panel title="Upcoming family tasks"><div className="space-y-2">{tasks.map(t=><div key={t.id} className="flex items-center justify-between gap-3 rounded-lg border border-white/10 p-2 text-sm"><div><b className={t.status==="Completed"?"line-through text-slate-500":""}>{t.title}</b><p className="text-xs text-slate-500">{t.due_date||"No date"} · {members.find(m=>m.id===t.member_id)?.name||"Family"} · {t.responsible||"Me"} · remind {t.reminder_days??2}d before</p></div><div className="flex gap-1"><button onClick={()=>toggle(t)} className="rounded-lg border border-white/10 px-2 py-1 text-xs">{t.status==="Completed"?"Reopen":"Done"}</button><button onClick={()=>editTask(t)} className="rounded-lg border border-white/10 px-2 py-1 text-xs">Edit</button><button onClick={()=>removeTask(t)} className="rounded-lg border border-red-400/20 px-2 py-1 text-xs text-red-300">Delete</button></div></div>)}</div></Panel>
      <Panel title="Baby dashboard"><form onSubmit={addBaby} className="grid gap-2 md:grid-cols-2"><input required value={babyTitle} onChange={e=>setBabyTitle(e.target.value)} placeholder="Record title"/><select value={babyType} onChange={e=>setBabyType(e.target.value)}>{["Weight","Doctor Visit","Vaccination","Feeding","Sleep","Milestone","Medicine","Document"].map(x=><option key={x}>{x}</option>)}</select><input type="date" value={babyDate} onChange={e=>setBabyDate(e.target.value)}/><input value={babyValue} onChange={e=>setBabyValue(e.target.value)} placeholder="Value / detail e.g. 5.6 kg"/><textarea value={babyNotes} onChange={e=>setBabyNotes(e.target.value)} placeholder="Notes" className="md:col-span-2"/><button className="primary-btn md:col-span-2">Add baby record</button></form><div className="mt-3 space-y-2">{baby.slice(0,20).map(r=><div key={r.id} className="flex items-center justify-between gap-3 rounded-lg border border-white/10 p-2 text-sm"><div><b>{r.title}</b><p className="text-xs text-slate-500">{r.date} · {r.type}{r.value?" · "+r.value:""}</p>{r.notes&&<p className="text-xs text-slate-400">{r.notes}</p>}</div><div className="flex gap-1"><button onClick={()=>editBaby(r)} className="mini-btn">Edit</button><button onClick={()=>removeBaby(r)} className="mini-btn text-red-300">Delete</button></div></div>)}</div></Panel>
    </div>}
  </main>;
}
