"use client";

import { FormEvent,useCallback,useEffect,useState } from "react";
import Link from "next/link";
import { BackHome,Panel } from "@/components/ui";
import { supabaseBrowser } from "@/lib/supabase/client";
import { currentWorkspace } from "@/lib/supabase/workspace";

const ALL_MODULES=["tasks","money","health","self_control","journal","family","baby","calendar","europe","business"];
type Member={workspace_id:string;user_id:string;role:string;modules:string[]};
type Invite={id:string;email:string;role:string;modules:string[];token:string;expires_at:string;accepted_at:string|null;accepted_by:string|null};

export default function AccessPage(){
 const[workspaceId,setWorkspaceId]=useState("");const[userId,setUserId]=useState("");const[roleNow,setRoleNow]=useState("");const[members,setMembers]=useState<Member[]>([]);const[invites,setInvites]=useState<Invite[]>([]);const[email,setEmail]=useState("");const[role,setRole]=useState("member");const[modules,setModules]=useState<string[]>(["tasks","family","baby","calendar"]);const[error,setError]=useState("");const[msg,setMsg]=useState("");
 const load=useCallback(async()=>{try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx){setWorkspaceId("");return;}setWorkspaceId(ctx.workspaceId);setUserId(ctx.user.id);setRoleNow(ctx.role);if(!["owner","admin"].includes(ctx.role))return;const[m,i]=await Promise.all([sb.from("workspace_members").select("workspace_id,user_id,role,modules").eq("workspace_id",ctx.workspaceId),sb.from("workspace_invitations").select("id,email,role,modules,token,expires_at,accepted_at,accepted_by").eq("workspace_id",ctx.workspaceId).order("created_at",{ascending:false})]);if(m.error)throw m.error;if(i.error)throw i.error;setMembers((m.data||[]) as Member[]);setInvites((i.data||[]) as Invite[]);}catch(e){setError(e instanceof Error?e.message:"Could not load workspace access");}},[]);useEffect(()=>{void load();},[load]);
 function toggleModule(m:string){setModules(v=>v.includes(m)?v.filter(x=>x!==m):[...v,m]);}
 async function invite(e:FormEvent){e.preventDefault();if(!email.trim())return;setError("");setMsg("");const sb=supabaseBrowser();const{data,error:q}=await sb.from("workspace_invitations").insert({workspace_id:workspaceId,email:email.trim().toLowerCase(),role,modules,created_by:userId}).select("token").single();if(q){setError(q.message);return;}const url=`${location.origin}/join?token=${data.token}`;try{await navigator.clipboard.writeText(url);setMsg("Invitation created and link copied. No email was sent automatically.");}catch{setMsg(`Invitation created: ${url}`);}setEmail("");await load();}
 async function revoke(id:string){if(!confirm("Revoke this invitation?"))return;const sb=supabaseBrowser();const{error:q}=await sb.from("workspace_invitations").delete().eq("id",id);if(q)setError(q.message);else await load();}
 async function updateMember(member:Member,patch:Partial<Member>){if(member.role==="owner")return;const sb=supabaseBrowser();const{error:q}=await sb.from("workspace_members").update(patch).eq("workspace_id",workspaceId).eq("user_id",member.user_id);if(q)setError(q.message);else await load();}
 async function removeMember(member:Member){if(member.role==="owner"||!confirm("Remove this member from the workspace?"))return;const sb=supabaseBrowser();const{error:q}=await sb.from("workspace_members").delete().eq("workspace_id",workspaceId).eq("user_id",member.user_id);if(q)setError(q.message);else await load();}

 return <main className="pt-6"><BackHome/><p className="mt-2 text-[11px] tracking-widest text-slate-400">ACCESS CONTROL</p><h1 className="text-2xl font-bold">Workspace sharing</h1><p className="mt-1 text-sm text-slate-400">Module grants are enforced by Supabase RLS, not just hidden in the UI.</p>{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}{msg&&<p className="mt-3 text-sm text-emerald-300">{msg}</p>}
 {!workspaceId?<p className="panel mt-4 p-5 text-sm">Sign in first. <Link href="/login" className="text-[#8ab6ff]">Login →</Link></p>:!["owner","admin"].includes(roleNow)?<div className="panel mt-4 p-5 text-sm text-slate-400">Only workspace Owner/Admin can manage access.</div>:<div className="mt-4 grid gap-4 md:grid-cols-[.75fr_1.25fr]">
 <Panel title="Invite member" kicker="LINK-BASED · 7 DAYS"><form onSubmit={invite} className="space-y-3"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><select value={role} onChange={e=>setRole(e.target.value)} className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"><option value="member">Member</option><option value="viewer">Viewer</option>{roleNow==="owner"&&<option value="admin">Admin</option>}</select><div className="grid grid-cols-2 gap-2">{ALL_MODULES.map(m=><label key={m} className="flex items-center gap-2 rounded border border-white/10 p-2 text-xs"><input type="checkbox" checked={modules.includes(m)} onChange={()=>toggleModule(m)}/>{m.replace("_"," ")}</label>)}</div><button className="w-full rounded-lg bg-[#77adff] p-2 font-bold text-[#06101f]">Create & copy invite link</button></form><div className="mt-4 space-y-2">{invites.filter(i=>!i.accepted_at).map(i=><div key={i.id} className="rounded-lg border border-white/10 p-2 text-xs"><b>{i.email}</b><p className="text-slate-500">{i.role} · {i.modules.join(", ")} · expires {new Date(i.expires_at).toLocaleDateString()}</p><button onClick={()=>revoke(i.id)} className="mt-1 text-red-300">Revoke</button></div>)}</div></Panel>
 <Panel title="Members"><div className="space-y-3">{members.map(m=><div key={m.user_id} className="rounded-xl border border-white/10 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div><b>{m.user_id===userId?"You":invites.find(i=>i.accepted_by===m.user_id)?.email||`Member ${m.user_id.slice(0,8)}`}</b><p className="text-xs text-slate-500">{m.role}</p></div>{m.role!=="owner"&&<div className="flex gap-2"><select value={m.role} onChange={e=>updateMember(m,{role:e.target.value})} className="rounded border border-white/10 bg-[#0a1524] p-1 text-xs"><option value="member">Member</option><option value="viewer">Viewer</option>{roleNow==="owner"&&<option value="admin">Admin</option>}</select><button onClick={()=>removeMember(m)} className="text-xs text-red-300">Remove</button></div>}</div><div className="mt-2 flex flex-wrap gap-1">{ALL_MODULES.map(mod=><button disabled={m.role==="owner"||m.role==="admin"} key={mod} onClick={()=>updateMember(m,{modules:m.modules.includes(mod)?m.modules.filter(x=>x!==mod):[...m.modules,mod]})} className={`rounded px-2 py-1 text-[10px] ${m.role==="owner"||m.role==="admin"||m.modules.includes(mod)?"bg-[#77adff]/15 text-[#9fc4ff]":"border border-white/10 text-slate-500"}`}>{mod.replace("_"," ")}</button>)}</div></div>)}</div></Panel></div>}
 </main>;
}
