"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { PrivacyGate } from "@/components/privacy-gate";
import Link from "next/link";
import { BackHome, Panel } from "@/components/ui";
import { supabaseBrowser } from "@/lib/supabase/client";
import { currentWorkspace } from "@/lib/supabase/workspace";
import { todayInTZ } from "@/lib/timezone";

type Entry={id:string;date:string;mood:string|null;body:string;tags:string[]|null;created_at:string};
type Photo={id:string;owner_id:string;path:string;created_at:string;url?:string|null};

function JournalContent(){
 const[workspaceId,setWorkspaceId]=useState("");const[userId,setUserId]=useState("");const[rows,setRows]=useState<Entry[]>([]);const[photos,setPhotos]=useState<Photo[]>([]);const[editingId,setEditingId]=useState<string|null>(null);const[body,setBody]=useState("");const[mood,setMood]=useState("Neutral");const[tags,setTags]=useState("");const[q,setQ]=useState("");const[error,setError]=useState("");const[msg,setMsg]=useState("");const[listening,setListening]=useState(false);const[pendingPhoto,setPendingPhoto]=useState<File|null>(null);
 const load=useCallback(async()=>{try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx){setWorkspaceId("");return;}setWorkspaceId(ctx.workspaceId);setUserId(ctx.user.id);const{data,error:x}=await sb.from("journal_entries").select("id,date,mood,body,tags,created_at").eq("workspace_id",ctx.workspaceId).order("created_at",{ascending:false}).limit(200);if(x)throw x;const entries=(data||[]) as Entry[];setRows(entries);const ids=entries.map(x=>x.id);if(ids.length){const a=await sb.from("attachments").select("id,owner_id,path,created_at").eq("workspace_id",ctx.workspaceId).eq("owner_table","journal_entries").in("owner_id",ids);if(a.error)throw a.error;const signed=await Promise.all(((a.data||[]) as Photo[]).map(async p=>{const s=await sb.storage.from("lifeos-private").createSignedUrl(p.path,900);return{...p,url:s.data?.signedUrl||null};}));setPhotos(signed);}else setPhotos([]);}catch(e){setError(e instanceof Error?e.message:"Could not load journal");}},[]);useEffect(()=>{void load();},[load]);
 async function add(e:FormEvent){e.preventDefault();if(!body.trim())return;setMsg("");const sb=supabaseBrowser();const payload={mood,body:body.trim(),tags:tags.split(",").map(x=>x.trim()).filter(Boolean),privacy:"private"};let entryId=editingId;if(editingId){const q=await sb.from("journal_entries").update(payload).eq("id",editingId);if(q.error){setError(q.error.message);return;}}else{const q=await sb.from("journal_entries").insert({...payload,workspace_id:workspaceId,created_by:userId,date:todayInTZ()}).select("id").single();if(q.error){setError(q.error.message);return;}entryId=q.data.id;}if(pendingPhoto&&entryId)await uploadPhoto(entryId,pendingPhoto);setEditingId(null);setBody("");setTags("");setPendingPhoto(null);setMsg("Journal entry saved privately.");await load();}
 function edit(r:Entry){setEditingId(r.id);setMood(r.mood||"Neutral");setBody(r.body);setTags((r.tags||[]).join(", "));window.scrollTo({top:0,behavior:"smooth"});}
 function cancelEdit(){setEditingId(null);setBody("");setTags("");setPendingPhoto(null);}
 function voiceCapture(){setMsg("");const w=window as unknown as {SpeechRecognition?:new()=>any;webkitSpeechRecognition?:new()=>any};const Recognition=w.SpeechRecognition||w.webkitSpeechRecognition;if(!Recognition){setMsg("Voice capture is not supported in this browser.");return;}const rec=new Recognition();rec.lang="en-US";rec.interimResults=false;rec.maxAlternatives=1;setListening(true);rec.onresult=(event:any)=>{const spoken=event.results?.[0]?.[0]?.transcript;if(spoken)setBody(v=>(v?v+"\n":"")+String(spoken));};rec.onerror=()=>setMsg("Voice capture failed or permission was denied.");rec.onend=()=>setListening(false);rec.start();}
 async function uploadPhoto(entryId:string,file:File){if(!workspaceId||!userId)return;const sb=supabaseBrowser();const id=crypto.randomUUID();const ext=(file.name.split(".").pop()||"jpg").replace(/[^a-zA-Z0-9]/g,"").slice(0,8)||"jpg";const path=workspaceId+"/"+userId+"/journal/"+entryId+"/"+id+"."+ext;const up=await sb.storage.from("lifeos-private").upload(path,file,{upsert:false,contentType:file.type||"image/jpeg"});if(up.error){setError(up.error.message);return;}const ins=await sb.from("attachments").insert({id,workspace_id:workspaceId,owner_table:"journal_entries",owner_id:entryId,path,created_by:userId});if(ins.error){await sb.storage.from("lifeos-private").remove([path]);setError(ins.error.message);}}
 async function removePhoto(p:Photo){if(!confirm("Delete this journal photo?"))return;const sb=supabaseBrowser();const q=await sb.from("attachments").delete().eq("id",p.id);if(q.error){setError(q.error.message);return;}await sb.storage.from("lifeos-private").remove([p.path]);await load();}
 async function remove(id:string){if(!confirm("Delete this journal entry?"))return;const sb=supabaseBrowser();const{error:x}=await sb.from("journal_entries").delete().eq("id",id);if(x)setError(x.message);else await load();}
 const filtered=useMemo(()=>{const n=q.toLowerCase().trim();return n?rows.filter(r=>(r.body+" "+(r.tags||[]).join(" ")+" "+r.mood).toLowerCase().includes(n)):rows;},[rows,q]);

 return <main className="pt-6"><BackHome/><p className="mt-2 text-[11px] tracking-widest text-slate-400">PRIVATE JOURNAL</p><h1 className="text-2xl font-bold">Notes, patterns, decisions</h1>{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}{msg&&<p className="mt-3 text-sm text-emerald-300">{msg}</p>}
 {!workspaceId?<p className="panel mt-4 p-5 text-sm">Sign in first. <Link href="/login" className="text-[#8ab6ff]">Login →</Link></p>:<div className="mt-4 grid gap-4 md:grid-cols-[.75fr_1.25fr]"><Panel title={editingId?"Edit entry":"New entry"}><form onSubmit={add} className="space-y-2"><select value={mood} onChange={e=>setMood(e.target.value)} className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2">{["Strong","Good","Neutral","Tired","Stressed","Low"].map(x=><option key={x}>{x}</option>)}</select><textarea required rows={8} value={body} onChange={e=>setBody(e.target.value)} placeholder="Write what happened, what you learned, or what needs attention." className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><div className="grid grid-cols-2 gap-2"><button type="button" onClick={voiceCapture} disabled={listening} className="ghost-btn">{listening?"Listening…":"Voice"}</button><label className="ghost-btn text-center cursor-pointer">{pendingPhoto?"Photo selected":"Photo / Camera"}<input type="file" accept="image/*" capture="environment" className="hidden" onChange={e=>setPendingPhoto(e.target.files?.[0]||null)}/></label></div><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="tags, comma, separated" className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><button className="w-full rounded-lg bg-[#77adff] p-2 font-bold text-[#06101f]">{editingId?"Update privately":"Save privately"}</button>{editingId&&<button type="button" onClick={cancelEdit} className="w-full rounded-lg border border-white/10 p-2">Cancel edit</button>}</form></Panel><Panel title="Entries"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search journal…" className="mb-3 w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><div className="space-y-2">{filtered.map(r=><article key={r.id} className="rounded-xl border border-white/10 p-3"><div className="flex justify-between gap-3"><span className="text-xs text-slate-500">{r.date} · {r.mood}</span><div className="flex gap-2"><button onClick={()=>edit(r)} className="text-xs text-[#8ab6ff]">Edit</button><button onClick={()=>remove(r.id)} className="text-xs text-red-300">Delete</button></div></div><p className="mt-2 whitespace-pre-wrap text-sm">{r.body}</p>{photos.filter(p=>p.owner_id===r.id).length>0&&<div className="mt-2 grid grid-cols-2 gap-2">{photos.filter(p=>p.owner_id===r.id).map(p=><div key={p.id} className="relative">{p.url&&<img src={p.url} alt="Journal attachment" className="h-32 w-full rounded-lg object-cover"/>}<button onClick={()=>removePhoto(p)} className="absolute right-1 top-1 rounded bg-black/60 px-2 py-1 text-xs text-white">×</button></div>)}</div>}{(r.tags||[]).length>0&&<p className="mt-2 text-xs text-[#9fc4ff]">{(r.tags||[]).map(t=>`#${t}`).join(" ")}</p>}</article>)}</div></Panel></div>}
 </main>;
}


export default function JournalPage(){return <PrivacyGate><JournalContent/></PrivacyGate>;}
