"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { BackHome, Panel } from "@/components/ui";
import { supabaseBrowser } from "@/lib/supabase/client";
import { currentWorkspace } from "@/lib/supabase/workspace";
import { useRealtimeRefresh } from "@/lib/use-realtime-refresh";

type Country={id:string;country:string;route:string|null;status:string;progress:number|null;notes:string|null};
type Route={id:string;country_id:string;route:string|null;requirements:string|null;cost_estimate:number|null;documents:string|null;language:string|null;timeline:string|null;next_action:string|null};
type Doc={id:string;country_id:string|null;name:string;owner:string|null;status:string;issue_date:string|null;expiry_date:string|null;needs_attestation:boolean;notes:string|null};
const PIPELINE=["Research","Shortlisted","Preparing","Application","Submitted","Waiting","Approved","Rejected"];

export default function EuropePage(){
 const[workspaceId,setWorkspaceId]=useState("");const[userId,setUserId]=useState("");const[countries,setCountries]=useState<Country[]>([]);const[routes,setRoutes]=useState<Route[]>([]);const[docs,setDocs]=useState<Doc[]>([]);const[error,setError]=useState("");
 const[country,setCountry]=useState("");const[route,setRoute]=useState("Study");
 const[routeCountry,setRouteCountry]=useState("");const[routeName,setRouteName]=useState("Study");const[requirements,setRequirements]=useState("");const[cost,setCost]=useState<number|undefined>();const[language,setLanguage]=useState("");const[timeline,setTimeline]=useState("");const[nextAction,setNextAction]=useState("");
 const[docName,setDocName]=useState("");const[docCountry,setDocCountry]=useState("");const[docOwner,setDocOwner]=useState("Me");const[docStatus,setDocStatus]=useState("Missing");const[docExpiry,setDocExpiry]=useState("");const[attest,setAttest]=useState(false);

 const load=useCallback(async()=>{try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx){setWorkspaceId("");return;}setWorkspaceId(ctx.workspaceId);setUserId(ctx.user.id);
  const[c,d]=await Promise.all([sb.from("migration_countries").select("id,country,route,status,progress,notes").eq("workspace_id",ctx.workspaceId).order("created_at"),sb.from("migration_documents").select("id,country_id,name,owner,status,issue_date,expiry_date,needs_attestation,notes").eq("workspace_id",ctx.workspaceId).order("created_at")]);if(c.error)throw c.error;if(d.error)throw d.error;const countryRows=(c.data||[]) as Country[];setCountries(countryRows);setDocs((d.data||[]) as Doc[]);
  const ids=countryRows.map(x=>x.id);if(ids.length){const rr=await sb.from("migration_routes").select("id,country_id,route,requirements,cost_estimate,documents,language,timeline,next_action").in("country_id",ids);if(rr.error)throw rr.error;setRoutes((rr.data||[]) as Route[]);}else setRoutes([]);
  if(countryRows[0]){setRouteCountry(v=>v||countryRows[0].id);setDocCountry(v=>v||countryRows[0].id);}
 }catch(e){setError(e instanceof Error?e.message:"Could not load relocation data");}},[]);
 useEffect(()=>{void load();},[load]);useRealtimeRefresh(["migration_countries","migration_documents"],load,Boolean(workspaceId));

 const ready=useMemo(()=>docs.filter(d=>d.status==="Ready").length,[docs]);
 async function addCountry(e:FormEvent){e.preventDefault();if(!workspaceId||!country.trim())return;const sb=supabaseBrowser();const{error:q}=await sb.from("migration_countries").insert({workspace_id:workspaceId,created_by:userId,country:country.trim(),route,status:"Research",progress:0});if(q)setError(q.message);else{setCountry("");await load();}}
 async function updateCountry(id:string,patch:Record<string,unknown>){const sb=supabaseBrowser();const{error:q}=await sb.from("migration_countries").update(patch).eq("id",id);if(q)setError(q.message);else await load();}
 async function saveRoute(e:FormEvent){e.preventDefault();if(!routeCountry)return;const sb=supabaseBrowser();const existing=routes.find(r=>r.country_id===routeCountry&&r.route===routeName);const payload={country_id:routeCountry,route:routeName,requirements:requirements.trim()||null,cost_estimate:cost??null,language:language.trim()||null,timeline:timeline.trim()||null,next_action:nextAction.trim()||null};const q=existing?await sb.from("migration_routes").update(payload).eq("id",existing.id):await sb.from("migration_routes").insert(payload);if(q.error)setError(q.error.message);else{setRequirements("");setCost(undefined);setLanguage("");setTimeline("");setNextAction("");await load();}}
 async function addDoc(e:FormEvent){e.preventDefault();if(!workspaceId||!docName.trim())return;const sb=supabaseBrowser();const{error:q}=await sb.from("migration_documents").insert({workspace_id:workspaceId,created_by:userId,country_id:docCountry||null,name:docName.trim(),owner:docOwner.trim()||"Me",status:docStatus,expiry_date:docExpiry||null,needs_attestation:attest});if(q)setError(q.message);else{setDocName("");setDocExpiry("");setAttest(false);await load();}}
 async function updateDoc(id:string,patch:Record<string,unknown>){const sb=supabaseBrowser();const{error:q}=await sb.from("migration_documents").update(patch).eq("id",id);if(q)setError(q.message);else await load();}

 return <main className="pt-6"><BackHome/><p className="mt-2 text-[11px] tracking-widest text-slate-400">RELOCATION COMMAND CENTER</p><h1 className="text-2xl font-bold">Family move to Europe</h1><p className="mt-1 text-sm text-slate-400">Store your researched routes and documents here. Immigration rules change, so legal/timeline facts should be verified against current official sources before decisions.</p>{error&&<p className="mt-3 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}
 {!workspaceId?<p className="panel mt-4 p-5 text-sm">Sign in to track relocation. <Link href="/login" className="text-[#8ab6ff]">Login →</Link></p>:<>
 <div className="mt-4 grid gap-4 md:grid-cols-3">{countries.map(c=><div key={c.id} className="panel p-4"><div className="flex justify-between gap-2"><div><b>{c.country}</b><p className="text-xs text-slate-400">{c.route||"Route not set"}</p></div><input aria-label="Country progress" type="number" min="0" max="100" value={c.progress||0} onChange={e=>updateCountry(c.id,{progress:Math.max(0,Math.min(100,Number(e.target.value)))})} className="h-8 w-16 rounded border border-white/10 bg-[#0a1524] p-1 text-xs"/></div><select value={c.status} onChange={e=>updateCountry(c.id,{status:e.target.value})} className="mt-3 w-full rounded-lg border border-white/10 bg-[#0a1524] p-1 text-xs">{PIPELINE.map(x=><option key={x}>{x}</option>)}</select><div className="mt-3 h-2 overflow-hidden rounded bg-white/10"><div className="h-full bg-[#77adff]" style={{width:`${Math.max(0,Math.min(100,Number(c.progress||0)))}%`}}/></div><p className="mt-2 text-xs text-slate-500">{docs.filter(d=>d.country_id===c.id&&d.status==="Ready").length}/{docs.filter(d=>d.country_id===c.id).length} docs ready</p></div>)}</div>
 <div className="mt-4 grid gap-4 md:grid-cols-2"><Panel title="Add country"><form onSubmit={addCountry} className="grid grid-cols-[1fr_130px_auto] gap-2"><input required value={country} onChange={e=>setCountry(e.target.value)} placeholder="Country" className="rounded-lg border border-white/10 bg-[#0a1524] p-2"/><select value={route} onChange={e=>setRoute(e.target.value)} className="rounded-lg border border-white/10 bg-[#0a1524] p-2">{["Study","Work","Business","Investment","Family"].map(x=><option key={x}>{x}</option>)}</select><button className="rounded-lg border border-white/10 px-3">Add</button></form></Panel>
 <Panel title="Route research"><form onSubmit={saveRoute} className="space-y-2"><div className="grid grid-cols-2 gap-2"><select value={routeCountry} onChange={e=>setRouteCountry(e.target.value)} className="rounded-lg border border-white/10 bg-[#0a1524] p-2">{countries.map(c=><option key={c.id} value={c.id}>{c.country}</option>)}</select><select value={routeName} onChange={e=>setRouteName(e.target.value)} className="rounded-lg border border-white/10 bg-[#0a1524] p-2">{["Study","Work","Business","Investment","Family"].map(x=><option key={x}>{x}</option>)}</select></div><textarea value={requirements} onChange={e=>setRequirements(e.target.value)} placeholder="Requirements / eligibility" className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><div className="grid grid-cols-2 gap-2"><input type="number" min="0" value={cost??""} onChange={e=>setCost(e.target.value?Number(e.target.value):undefined)} placeholder="Estimated cost" className="rounded-lg border border-white/10 bg-[#0a1524] p-2"/><input value={language} onChange={e=>setLanguage(e.target.value)} placeholder="Language requirement" className="rounded-lg border border-white/10 bg-[#0a1524] p-2"/></div><input value={timeline} onChange={e=>setTimeline(e.target.value)} placeholder="Timeline / PR / citizenship notes" className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><input value={nextAction} onChange={e=>setNextAction(e.target.value)} placeholder="Next action" className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><button className="w-full rounded-lg border border-white/10 p-2">Save route research</button></form></Panel></div>
 <Panel title="Saved route comparisons" kicker="YOUR RESEARCH, NOT AUTOMATIC LEGAL ADVICE"><div className="grid gap-2 md:grid-cols-2">{routes.map(r=><div key={r.id} className="rounded-xl border border-white/10 p-3 text-sm"><b>{countries.find(c=>c.id===r.country_id)?.country||"Country"} · {r.route}</b><p className="mt-1 text-xs text-slate-400">{r.requirements||"No requirements recorded"}</p><div className="mt-2 grid grid-cols-2 gap-1 text-xs"><span>Cost: {r.cost_estimate==null?"—":Number(r.cost_estimate).toLocaleString()}</span><span>Language: {r.language||"—"}</span><span>Timeline: {r.timeline||"—"}</span><span>Next: {r.next_action||"—"}</span></div></div>)}</div></Panel>
 <Panel title="Document readiness" kicker={docs.length?`${ready}/${docs.length} READY`:"NO DOCUMENTS"}><form onSubmit={addDoc} className="grid gap-2 md:grid-cols-6"><input required value={docName} onChange={e=>setDocName(e.target.value)} placeholder="Document" className="rounded-lg border border-white/10 bg-[#0a1524] p-2 md:col-span-2"/><select value={docCountry} onChange={e=>setDocCountry(e.target.value)} className="rounded-lg border border-white/10 bg-[#0a1524] p-2"><option value="">General</option>{countries.map(c=><option key={c.id} value={c.id}>{c.country}</option>)}</select><input value={docOwner} onChange={e=>setDocOwner(e.target.value)} placeholder="Owner" className="rounded-lg border border-white/10 bg-[#0a1524] p-2"/><input type="date" value={docExpiry} onChange={e=>setDocExpiry(e.target.value)} className="rounded-lg border border-white/10 bg-[#0a1524] p-2"/><button className="rounded-lg bg-[#77adff] p-2 font-bold text-[#06101f]">Add</button><label className="md:col-span-6 flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" checked={attest} onChange={e=>setAttest(e.target.checked)}/>Needs attestation</label></form><div className="mt-3 space-y-2">{docs.map(d=><div key={d.id} className="grid gap-2 rounded-lg border border-white/10 p-2 text-sm md:grid-cols-[1fr_160px_120px]"><div><b>{d.name}</b><p className="text-xs text-slate-500">{countries.find(c=>c.id===d.country_id)?.country||"General"} · owner {d.owner||"Me"}{d.expiry_date?` · expires ${d.expiry_date}`:""}{d.needs_attestation?" · attestation needed":""}</p></div><select value={d.status} onChange={e=>updateDoc(d.id,{status:e.target.value})} className="rounded-lg border border-white/10 bg-[#0a1524] p-1">{["Ready","Missing","Pending","Needs Attestation","Expired"].map(x=><option key={x}>{x}</option>)}</select><input type="date" value={d.expiry_date||""} onChange={e=>updateDoc(d.id,{expiry_date:e.target.value||null})} className="rounded-lg border border-white/10 bg-[#0a1524] p-1 text-xs"/></div>)}</div></Panel>
 </>}
 </main>;
}
