"use client";
import { FormEvent, useEffect, useState } from "react";
import { BackHome, Panel } from "@/components/ui";
import { supabaseBrowser } from "@/lib/supabase/client";
import { currentWorkspaceId } from "@/lib/supabase/workspace";
type Reminder={id:string;kind:string;title:string;time:string|null;target:number|null;unit:string|null;enabled:boolean};
type Sleep={id:string;sleep_date:string;bedtime:string|null;wake_time:string|null;duration_hours:number|null;quality:number|null};
type Diet={id:string;meal:string;title:string;target_time:string|null;protein_g:number|null};
type Health={id:string;date:string;weight:number|null};
export default function HealthPage(){
 const [workspace,setWorkspace]=useState(""); const [msg,setMsg]=useState("Loading…");
 const [reminders,setReminders]=useState<Reminder[]>([]); const [sleep,setSleep]=useState<Sleep[]>([]); const [diet,setDiet]=useState<Diet[]>([]); const [weights,setWeights]=useState<Health[]>([]);
 const sb=supabaseBrowser();
 async function load(){try{const ws=await currentWorkspaceId(sb);setWorkspace(ws);const [r,s,d,w]=await Promise.all([sb.from("health_reminders").select("id,kind,title,time,target,unit,enabled").eq("workspace_id",ws).order("time"),sb.from("sleep_logs").select("id,sleep_date,bedtime,wake_time,duration_hours,quality").eq("workspace_id",ws).order("sleep_date",{ascending:false}).limit(14),sb.from("diet_plan_items").select("id,meal,title,target_time,protein_g").eq("workspace_id",ws).eq("active",true).order("target_time"),sb.from("health_entries").select("id,date,weight").eq("workspace_id",ws).not("weight","is",null).order("date",{ascending:false}).limit(30)]);const err=r.error||s.error||d.error||w.error;if(err)throw err;setReminders(r.data||[]);setSleep(s.data||[]);setDiet(d.data||[]);setWeights(w.data||[]);setMsg("");}catch(e){setMsg(e instanceof Error?e.message:"Could not load health data");}}
 useEffect(()=>{void load();},[]);
 async function addReminder(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {data:u}=await sb.auth.getUser();const {error}=await sb.from("health_reminders").insert({workspace_id:workspace,kind:f.get("kind"),title:f.get("title"),time:f.get("time")||null,target:Number(f.get("target"))||null,unit:f.get("unit")||null,created_by:u.user?.id});if(error)setMsg(error.message);else{e.currentTarget.reset();await load();}}
 async function addWeight(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {data:u}=await sb.auth.getUser();const {error}=await sb.from("health_entries").insert({workspace_id:workspace,date:f.get("date"),weight:Number(f.get("weight")),privacy:"private",created_by:u.user?.id});if(error)setMsg(error.message);else{e.currentTarget.reset();await load();}}
 async function addSleep(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {data:u}=await sb.auth.getUser();const {error}=await sb.from("sleep_logs").insert({workspace_id:workspace,sleep_date:f.get("date"),bedtime:f.get("bedtime")||null,wake_time:f.get("wake")||null,duration_hours:Number(f.get("duration"))||null,quality:Number(f.get("quality"))||null,created_by:u.user?.id});if(error)setMsg(error.message);else{e.currentTarget.reset();await load();}}
 async function addDiet(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {data:u}=await sb.auth.getUser();const {error}=await sb.from("diet_plan_items").insert({workspace_id:workspace,meal:f.get("meal"),title:f.get("title"),target_time:f.get("time")||null,protein_g:Number(f.get("protein"))||null,created_by:u.user?.id});if(error)setMsg(error.message);else{e.currentTarget.reset();await load();}}
 async function toggleReminder(r:Reminder){await sb.from("health_reminders").update({enabled:!r.enabled}).eq("id",r.id);await load();}
 return <main className="pt-6"><BackHome/><p className="mt-2 text-[11px] tracking-widest text-slate-400">HEALTH COMMAND CENTER</p><h1 className="text-2xl font-bold">Health tracker</h1>{msg&&<p className="notice mt-3">{msg}</p>}<div className="mt-4 grid gap-4 md:grid-cols-2">
 <Panel title="Weight tracker" kicker="MOBILE QUICK LOG"><form onSubmit={addWeight} className="form-row"><input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/><input name="weight" type="number" step="0.1" placeholder="Weight kg" required/><button disabled={!workspace}>Save</button></form><div className="mini-list">{weights.map(x=><span key={x.id}><b>{x.weight} kg</b><small>{x.date}</small></span>)}</div></Panel>
 <Panel title="Water & medicine reminders" kicker="REMINDERS"><form onSubmit={addReminder} className="form-grid"><select name="kind"><option value="water">Water</option><option value="medicine">Medicine</option><option value="sleep">Sleep</option><option value="diet">Diet</option></select><input name="title" placeholder="Drink water / medicine" required/><input name="time" type="time"/><input name="target" type="number" step="0.1" placeholder="Target"/><input name="unit" placeholder="ml / tablet"/><button disabled={!workspace}>Add reminder</button></form><div className="mini-list">{reminders.map(r=><button className="list-button" key={r.id} onClick={()=>toggleReminder(r)}><b>{r.title}</b><small>{r.kind+" · "+(r.time||"any time")+" · "+(r.enabled?"ON":"OFF")}</small></button>)}</div></Panel>
 <Panel title="Diet plan" kicker="MEALS"><form onSubmit={addDiet} className="form-grid"><select name="meal"><option>Breakfast</option><option>Lunch</option><option>Dinner</option><option>Snack</option></select><input name="title" placeholder="Meal / food" required/><input name="time" type="time"/><input name="protein" type="number" step="0.1" placeholder="Protein g"/><button disabled={!workspace}>Add meal</button></form><div className="mini-list">{diet.map(x=><span key={x.id}><b>{x.meal+": "+x.title}</b><small>{(x.target_time||"Flexible")+(x.protein_g?" · "+x.protein_g+"g protein":"")}</small></span>)}</div></Panel>
 <Panel title="Sleep tracker" kicker="BED → WAKE"><form onSubmit={addSleep} className="form-grid"><input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/><input name="bedtime" type="time"/><input name="wake" type="time"/><input name="duration" type="number" step="0.1" placeholder="Hours"/><input name="quality" type="number" min="1" max="10" placeholder="Quality 1–10"/><button disabled={!workspace}>Log sleep</button></form><div className="mini-list">{sleep.map(x=><span key={x.id}><b>{(x.duration_hours??"—")+"h · quality "+(x.quality??"—")+"/10"}</b><small>{x.sleep_date+" · "+(x.bedtime||"—")+" → "+(x.wake_time||"—")}</small></span>)}</div></Panel>
 </div></main>;
}