"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { BackHome, Panel } from "@/components/ui";
import { remaining } from "@/lib/money";
import { habitConsistencyForFrequency } from "@/lib/habits";
import { supabaseBrowser } from "@/lib/supabase/client";
import { currentWorkspace,peekWorkspaceContext } from "@/lib/supabase/workspace";
import { todayInTZ } from "@/lib/timezone";

type Metrics={tasksDone:number;openTasks:number;focusMin:number;moneyReceived:number;moneyOpen:number;habitConsistency:number};

function addDays(iso:string,n:number){const d=new Date(iso+"T12:00:00");d.setDate(d.getDate()+n);return d.toISOString().slice(0,10);}
function monthStart(iso:string){return iso.slice(0,7)+"-01";}

export default function ReviewsPage(){
 const cachedWorkspace=peekWorkspaceContext();const[workspaceId,setWorkspaceId]=useState(cachedWorkspace?.workspaceId||"");const[userId,setUserId]=useState(cachedWorkspace?.user.id||"");const[metrics,setMetrics]=useState<Metrics|null>(null);const[previous,setPrevious]=useState<Metrics|null>(null);
 const[accomplishment,setAccomplishment]=useState("");const[incomplete,setIncomplete]=useState("");const[blocker,setBlocker]=useState("");const[improve,setImprove]=useState("");const[energy,setEnergy]=useState(7);const[error,setError]=useState("");const[msg,setMsg]=useState("");const[weeklyChecks,setWeeklyChecks]=useState<Record<string,boolean>>({review:true,inbox:false,overdue:false,money:false,health:false,projects:false,family:false,europe:false});const[topOutcomes,setTopOutcomes]=useState("");const[aiReview,setAiReview]=useState("");const[aiLabel,setAiLabel]=useState("");const[aiLoading,setAiLoading]=useState(false);
 const today=todayInTZ();

 const compute=useCallback(async(from:string,to:string,ws:string):Promise<Metrics>=>{const sb=supabaseBrowser();const[tasks,focus,recs,habits]=await Promise.all([
   sb.from("tasks").select("status,completed_at").eq("workspace_id",ws),
   sb.from("focus_sessions").select("date,minutes").eq("workspace_id",ws).gte("date",from).lte("date",to),
   sb.from("receivables").select("id,total,receivable_payments(amount,date)").eq("workspace_id",ws),
   sb.from("habits").select("id,frequency,target").eq("workspace_id",ws)
  ]);for(const q of[tasks,focus,recs,habits])if(q.error)throw q.error;
  const taskRows=(tasks.data||[]) as any[];const tasksDone=taskRows.filter(t=>t.status==="Completed"&&t.completed_at&&String(t.completed_at).slice(0,10)>=from&&String(t.completed_at).slice(0,10)<=to).length;const openTasks=taskRows.filter(t=>!["Completed","Cancelled"].includes(t.status)).length;
  let moneyReceived=0,moneyOpen=0;for(const r of (recs.data||[]) as any[]){const tx=(r.receivable_payments||[]) as any[];moneyOpen+=remaining(Number(r.total||0),tx.map(p=>({amount:Number(p.amount||0),date:p.date||today})));moneyReceived+=tx.filter(p=>p.date>=from&&p.date<=to).reduce((a,p)=>a+Number(p.amount||0),0);}
  const habitRows=(habits.data||[]) as {id:string;frequency:string;target:number|null}[];let consistency=0;if(habitRows.length){const habitIds=habitRows.map(h=>h.id);const logs=await sb.from("habit_logs").select("habit_id,date,value").in("habit_id",habitIds).gte("date",from).lte("date",to);if(logs.error)throw logs.error;const days:string[]=[];for(let d=new Date(from+"T12:00:00");d<=new Date(to+"T12:00:00");d.setDate(d.getDate()+1))days.push(d.toISOString().slice(0,10));const perHabit=habitRows.map(h=>{const map=Object.fromEntries((logs.data||[]).filter((l:any)=>l.habit_id===h.id).map((l:any)=>[l.date,Number(l.value||0)]));return habitConsistencyForFrequency(map,days,h.frequency||"Daily",Number(h.target||1));});consistency=Math.round(perHabit.reduce((a,b)=>a+b,0)/perHabit.length);}
  return{tasksDone,openTasks,focusMin:(focus.data||[]).reduce((a:any,s:any)=>a+Number(s.minutes||0),0),moneyReceived,moneyOpen,habitConsistency:Math.min(100,consistency)};},[today]);

 const load=useCallback(async()=>{try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx){setWorkspaceId("");return;}setWorkspaceId(ctx.workspaceId);setUserId(ctx.user.id);const currentFrom=monthStart(today);const prevEnd=addDays(currentFrom,-1);const prevFrom=monthStart(prevEnd);const[m,p]=await Promise.all([compute(currentFrom,today,ctx.workspaceId),compute(prevFrom,prevEnd,ctx.workspaceId)]);setMetrics(m);setPrevious(p);const daily=await sb.from("daily_reviews").select("accomplishment,incomplete,blocker,energy,improve").eq("workspace_id",ctx.workspaceId).eq("date",today).order("created_at",{ascending:false}).limit(1).maybeSingle();if(daily.data){setAccomplishment(daily.data.accomplishment||"");setIncomplete(daily.data.incomplete||"");setBlocker(daily.data.blocker||"");setEnergy(Number(daily.data.energy||7));setImprove(daily.data.improve||"");}}catch(e){setError(e instanceof Error?e.message:"Could not build review");}},[compute,today]);useEffect(()=>{void load();},[load]);

 async function saveDaily(e:FormEvent){e.preventDefault();const sb=supabaseBrowser();const existing=await sb.from("daily_reviews").select("id").eq("workspace_id",workspaceId).eq("date",today).order("created_at",{ascending:false}).limit(1).maybeSingle();const payload={workspace_id:workspaceId,created_by:userId,date:today,accomplishment,incomplete,blocker,energy,improve,snapshot:metrics||{}};const q=existing.data?await sb.from("daily_reviews").update(payload).eq("id",existing.data.id):await sb.from("daily_reviews").insert(payload);if(q.error)setError(q.error.message);else setMsg("Daily review saved.");}
 async function saveWeeklyPlan(){const sb=supabaseBrowser();const planning={checks:weeklyChecks,top_outcomes:topOutcomes.split("\n").map(x=>x.trim()).filter(Boolean).slice(0,5)};const existing=await sb.from("weekly_reviews").select("id,snapshot").eq("workspace_id",workspaceId).eq("date",today).order("created_at",{ascending:false}).limit(1).maybeSingle();const snapshot={...(existing.data?.snapshot||{}),...(metrics||{}),planning};const q=existing.data?await sb.from("weekly_reviews").update({snapshot}).eq("id",existing.data.id):await sb.from("weekly_reviews").insert({workspace_id:workspaceId,created_by:userId,date:today,snapshot});if(q.error)setError(q.error.message);else setMsg("Weekly planning saved.");}
 async function generateAiReview(){setAiLoading(true);setError("");try{const r=await fetch("/api/ai/weekly-review",{method:"POST"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Weekly AI review failed");setAiReview(j.answer||"");setAiLabel(j.label||"");}catch(e){setError(e instanceof Error?e.message:"Weekly AI review failed");}finally{setAiLoading(false);}}
 async function saveSnapshot(kind:"weekly"|"monthly"){if(!metrics)return;const sb=supabaseBrowser();if(kind==="weekly"){const q=await sb.from("weekly_reviews").insert({workspace_id:workspaceId,created_by:userId,date:today,snapshot:metrics});if(q.error){setError(q.error.message);return;}}else{const q=await sb.from("monthly_reviews").insert({workspace_id:workspaceId,created_by:userId,month:today.slice(0,7),snapshot:metrics});if(q.error){setError(q.error.message);return;}}setMsg(`${kind==="weekly"?"Weekly":"Monthly"} snapshot saved.`);}
 const delta=(key:keyof Metrics)=>!metrics||!previous?0:Number(metrics[key])-Number(previous[key]);

 return <main className="pt-6"><BackHome/><p className="mt-2 text-[11px] tracking-widest text-slate-400">REVIEWS</p><h1 className="text-2xl font-bold">Daily reflection, monthly evidence</h1>{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}{msg&&<p className="mt-3 text-sm text-emerald-300">{msg}</p>}
 {!workspaceId?<p className="panel mt-4 p-5 text-sm">Sign in first. <Link href="/login" className="text-[#8ab6ff]">Login →</Link></p>:<div className="mt-4 grid gap-4">
  <Panel title="This month" kicker="VS PREVIOUS MONTH"><div className="grid grid-cols-2 gap-2 md:grid-cols-6">{metrics&&(["tasksDone","focusMin","moneyReceived","moneyOpen","habitConsistency","openTasks"] as (keyof Metrics)[]).map(k=><div key={k} className="rounded-lg border border-white/10 p-3"><span className="text-[10px] uppercase text-slate-500">{k.replace(/[A-Z]/g,m=>" "+m).trim()}</span><b className="block text-lg">{k.startsWith("money")?`AED ${Number(metrics[k]).toLocaleString()}`:metrics[k]}</b><small className={delta(k)>=0?"text-emerald-300":"text-red-300"}>{delta(k)>=0?"+":""}{delta(k)} vs prev</small></div>)}</div><div className="mt-3 flex gap-2"><button onClick={()=>saveSnapshot("weekly")} className="rounded-lg border border-white/10 px-3 py-2 text-sm">Save weekly snapshot</button><button onClick={()=>saveSnapshot("monthly")} className="rounded-lg border border-white/10 px-3 py-2 text-sm">Save monthly snapshot</button></div></Panel>
  <Panel title="Weekly planning mode" kicker="SUNDAY RESET"><p className="text-sm text-slate-400">Review the week, clear loose ends, then choose next week&apos;s top outcomes.</p><div className="mt-3 grid gap-2 md:grid-cols-2">{[["review","Review last week"],["inbox","Clear inbox"],["overdue","Check overdue"],["money","Review money"],["health","Check health"],["projects","Review projects"],["family","Review family"],["europe","Review Europe"]].map(([key,label])=><label key={key} className="flex items-center gap-2 rounded-lg border border-white/10 p-2 text-sm"><input type="checkbox" checked={Boolean(weeklyChecks[key])} onChange={e=>setWeeklyChecks(v=>({...v,[key]:e.target.checked}))}/>{label}</label>)}</div><textarea value={topOutcomes} onChange={e=>setTopOutcomes(e.target.value)} rows={4} className="mt-3 w-full" placeholder={"Next week top outcomes, one per line\n1. Outstanding payments\n2. Sleep consistency\n3. Europe documents"}/><div className="mt-3 flex flex-wrap gap-2"><button onClick={saveWeeklyPlan} className="primary-btn">Save weekly plan</button><button onClick={generateAiReview} disabled={aiLoading} className="ghost-btn">{aiLoading?"Reviewing…":"AI weekly review"}</button></div>{aiReview&&<div className="mt-3 rounded-xl border border-white/10 p-3"><span className="label">{aiLabel}</span><p className="mt-2 whitespace-pre-wrap text-sm">{aiReview}</p></div>}</Panel>
  <Panel title="Night review" kicker={today}><form onSubmit={saveDaily} className="grid gap-3 md:grid-cols-2"><label className="text-xs text-slate-400">What went well?<textarea value={accomplishment} onChange={e=>setAccomplishment(e.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/></label><label className="text-xs text-slate-400">What stayed incomplete?<textarea value={incomplete} onChange={e=>setIncomplete(e.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/></label><label className="text-xs text-slate-400">Main blocker<textarea value={blocker} onChange={e=>setBlocker(e.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/></label><label className="text-xs text-slate-400">Improve tomorrow<textarea value={improve} onChange={e=>setImprove(e.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/></label><label className="text-xs text-slate-400">Energy {energy}/10<input type="range" min="1" max="10" value={energy} onChange={e=>setEnergy(Number(e.target.value))} className="w-full"/></label><button className="rounded-lg bg-[#77adff] p-2 font-bold text-[#06101f]">Save daily review</button></form></Panel>
 </div>}
 </main>;
}
