"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { BackHome, Panel } from "@/components/ui";
import { supabaseBrowser } from "@/lib/supabase/client";
import { currentWorkspace } from "@/lib/supabase/workspace";
import { useRealtimeRefresh } from "@/lib/use-realtime-refresh";
import { todayInTZ } from "@/lib/timezone";

type Project={id:string;name:string;area:string|null;deadline:string|null;status:string;owner:string|null;goal_id:string|null;notes:string|null};
type Goal={id:string;name:string};
type ProjectTask={id:string;project_id:string|null;name:string;status:string};

export default function ProjectsPage(){
 const[workspaceId,setWorkspaceId]=useState("");const[userId,setUserId]=useState("");const[projects,setProjects]=useState<Project[]>([]);const[goals,setGoals]=useState<Goal[]>([]);const[tasks,setTasks]=useState<ProjectTask[]>([]);const[open,setOpen]=useState<string|null>(null);
 const[editingId,setEditingId]=useState<string|null>(null);const[name,setName]=useState("");const[area,setArea]=useState("Business");const[goalId,setGoalId]=useState("");const[owner,setOwner]=useState("Me");const[notes,setNotes]=useState("");const[deadline,setDeadline]=useState(()=>{const d=new Date(todayInTZ()+"T12:00:00");d.setDate(d.getDate()+30);return d.toISOString().slice(0,10);});const[error,setError]=useState("");

 const load=useCallback(async()=>{try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx){setWorkspaceId("");return;}setWorkspaceId(ctx.workspaceId);setUserId(ctx.user.id);const[p,g,t]=await Promise.all([sb.from("projects").select("id,name,area,deadline,status,owner,goal_id,notes").eq("workspace_id",ctx.workspaceId).order("deadline",{ascending:true,nullsFirst:false}),sb.from("goals").select("id,name").eq("workspace_id",ctx.workspaceId),sb.from("tasks").select("id,project_id,name,status").eq("workspace_id",ctx.workspaceId).not("project_id","is",null)]);if(p.error)throw p.error;if(g.error)throw g.error;if(t.error)throw t.error;setProjects((p.data||[]) as Project[]);setGoals((g.data||[]) as Goal[]);setTasks((t.data||[]) as ProjectTask[]);}catch(e){setError(e instanceof Error?e.message:"Could not load projects");}},[]);
 useEffect(()=>{void load();},[load]);useRealtimeRefresh(["projects","tasks"],load,Boolean(workspaceId));
 const stats=useMemo(()=>new Map(projects.map(p=>{const pt=tasks.filter(t=>t.project_id===p.id);const done=pt.filter(t=>t.status==="Completed").length;return[p.id,{total:pt.length,done,progress:pt.length?Math.round(done/pt.length*100):0}];})),[projects,tasks]);

 async function add(e:FormEvent){e.preventDefault();if(!workspaceId||!name.trim())return;const sb=supabaseBrowser();const payload={name:name.trim(),area,goal_id:goalId||null,deadline,owner:owner.trim()||"Me",notes:notes.trim()||null,privacy:area==="Health"||area==="Self-control"?"private":"family",updated_at:new Date().toISOString()};const q=editingId?await sb.from("projects").update(payload).eq("id",editingId):await sb.from("projects").insert({...payload,workspace_id:workspaceId,created_by:userId,status:"Active"});if(q.error)setError(q.error.message);else{setEditingId(null);setName("");setNotes("");await load();}}
 async function setStatus(id:string,status:string){const sb=supabaseBrowser();const{error:q}=await sb.from("projects").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(q)setError(q.message);else await load();}
 function startEdit(p:Project){setEditingId(p.id);setName(p.name);setArea(p.area||"Business");setGoalId(p.goal_id||"");setOwner(p.owner||"Me");setNotes(p.notes||"");setDeadline(p.deadline||todayInTZ());window.scrollTo({top:0,behavior:"smooth"});}
 function cancelEdit(){setEditingId(null);setName("");setNotes("");}
 async function removeProject(p:Project){if(!confirm(`Delete project "${p.name}"? Its tasks will remain but become unlinked.`))return;const sb=supabaseBrowser();const{error:q}=await sb.from("projects").delete().eq("id",p.id);if(q)setError(q.message);else await load();}
 async function quickTask(p:Project){const title=prompt(`New task for ${p.name}:`);if(!title?.trim())return;const sb=supabaseBrowser();const{error:q}=await sb.from("tasks").insert({workspace_id:workspaceId,created_by:userId,name:title.trim(),area:p.area||"Business",project_id:p.id,goal_id:p.goal_id,status:"Inbox",importance:3,deadline:p.deadline,start_date:todayInTZ(),recurrence:{kind:"none"}});if(q)setError(q.message);else await load();}

 return <main className="pt-6"><BackHome/><p className="mt-2 text-[11px] tracking-widest text-slate-400">PROJECTS</p><h1 className="text-2xl font-bold">Execution layer</h1>{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}
 {!workspaceId?<p className="panel mt-4 p-5 text-sm">Sign in first. <Link href="/login" className="text-[#8ab6ff]">Login →</Link></p>:<div className="mt-4 grid gap-4 md:grid-cols-[.7fr_1.3fr]">
 <Panel title={editingId?"Edit project":"Add project"}><form onSubmit={add} className="space-y-2"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Project name" className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><select value={area} onChange={e=>setArea(e.target.value)} className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2">{["Business","Money","Health","Family","Europe","Growth","Personal","Self-control"].map(x=><option key={x}>{x}</option>)}</select><select value={goalId} onChange={e=>setGoalId(e.target.value)} className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"><option value="">No linked goal</option>{goals.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><div className="grid grid-cols-2 gap-2"><input value={owner} onChange={e=>setOwner(e.target.value)} placeholder="Owner" className="rounded-lg border border-white/10 bg-[#0a1524] p-2"/><input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)} className="rounded-lg border border-white/10 bg-[#0a1524] p-2"/></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Outcome / project notes" className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><button className="w-full rounded-lg bg-[#77adff] p-2 font-bold text-[#06101f]">{editingId?"Update project":"Save project"}</button>{editingId&&<button type="button" onClick={cancelEdit} className="w-full rounded-lg border border-white/10 p-2">Cancel edit</button>}</form></Panel>
 <Panel title="Projects"><div className="space-y-2">{projects.map(p=>{const s=stats.get(p.id)||{total:0,done:0,progress:0};const expanded=open===p.id;return <div key={p.id} className="rounded-xl border border-white/10 p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><b>{p.name}</b><p className="text-xs text-slate-500">{p.area} · owner {p.owner||"Me"} · due {p.deadline||"—"} · {goals.find(g=>g.id===p.goal_id)?.name||"No goal"}</p>{p.notes&&<p className="mt-1 text-xs text-slate-400">{p.notes}</p>}</div><div className="flex gap-2"><select value={p.status} onChange={e=>setStatus(p.id,e.target.value)} className="rounded-lg border border-white/10 bg-[#0a1524] p-1 text-xs"><option>Active</option><option>Paused</option><option>Completed</option><option>Cancelled</option></select><button onClick={()=>setOpen(expanded?null:p.id)} className="rounded border border-white/10 px-2 py-1 text-xs">Tasks</button><button onClick={()=>startEdit(p)} className="rounded border border-white/10 px-2 py-1 text-xs">Edit</button><button onClick={()=>removeProject(p)} className="rounded border border-red-400/20 px-2 py-1 text-xs text-red-300">Delete</button></div></div><div className="mt-2 h-2 overflow-hidden rounded bg-white/10"><div className="h-full bg-[#77adff]" style={{width:`${s.progress}%`}}/></div><p className="mt-1 text-xs text-slate-500">{s.done}/{s.total} tasks complete · {s.progress}%</p>{expanded&&<div className="mt-3 border-t border-white/10 pt-3">{tasks.filter(t=>t.project_id===p.id).map(t=><div key={t.id} className="mb-1 rounded bg-white/[.03] p-2 text-xs"><span className={t.status==="Completed"?"line-through text-slate-500":""}>{t.name}</span><span className="float-right text-slate-500">{t.status}</span></div>)}<button onClick={()=>quickTask(p)} className="mt-2 rounded border border-white/10 px-2 py-1 text-xs">+ Project task</button></div>}</div>})}</div></Panel>
 </div>}
 </main>;
}
