"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { previewLegacyImport } from "@/lib/legacy-import";
import { commitLegacyImport,type LegacyImportResult } from "@/lib/legacy-import-commit";
import { supabaseBrowser } from "@/lib/supabase/client";
import { currentWorkspace } from "@/lib/supabase/workspace";

function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
function csvCell(v:unknown){const s=String(v??"");return `"${s.replace(/"/g,'""')}"`;}

const featureLinks=[
 ["Home","/"],["Today","/today"],["Tasks","/tasks"],["Goals","/goals"],["Projects","/projects"],
 ["Money","/money"],["Waste Guard","/expenses"],["Business","/business"],["Health","/health"],["Health Planner","/health-planner"],["Family","/family"],["Europe","/europe"],
 ["Calendar","/calendar"],["Timeline","/timeline"],["Automations","/automations"],["Reviews","/reviews"],
 ["Journal","/journal"],["Sticky Notes","/sticky-notes"],["Habits","/habits"],["Focus","/focus"],["Time Tracking","/time"],
 ["Priority Matrix","/matrix"],["Waiting For","/waiting"],["Health Vault","/health-vault"],["Hair Recovery","/hair"],
 ["Self-Control","/self-control"],["Progress","/progress"],["AI Coach","/coach"],["Notifications","/notifications"],
 ["Privacy / PIN","/privacy"],["Access","/access"],["Search","/search"],["Quick Add","/quick-add"],["Mobile Tasks & Notes","/mobile"]
];

type GoogleStatus={authenticated:boolean;configured:boolean;connected:boolean;accountEmail?:string|null};
type DndBlock={id:string;label:string;start_time:string;end_time:string;days_of_week:number[];active:boolean};
type BackupFile={name:string;updated_at?:string|null;created_at?:string|null};
const HOME_WIDGETS=[["top3","Today Top 3"],["money","Money Due"],["health","Health"],["focus","Deep Work"],["family","Family"],["europe","Europe Progress"],["business","Business"],["calendar","Calendar"],["alerts","Alerts"],["waiting","Waiting For"],["goals","Goals"],["week","This Week"],["waste","Waste Guard"]] as const;

export default function SettingsPage(){
 const[preview,setPreview]=useState("");const[backup,setBackup]=useState<Record<string,unknown>|null>(null);const[result,setResult]=useState<LegacyImportResult|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[msg,setMsg]=useState("");
 const[timezone,setTimezone]=useState("Asia/Dubai");const[currency,setCurrency]=useState("AED");const[dailyFocus,setDailyFocus]=useState(120);const[weeklyFocus,setWeeklyFocus]=useState(600);const[quietStart,setQuietStart]=useState("22:30");const[quietEnd,setQuietEnd]=useState("07:00");const[allowCritical,setAllowCritical]=useState(false);const[userId,setUserId]=useState("");
 const[theme,setTheme]=useState<"dark"|"light">("dark");const[google,setGoogle]=useState<GoogleStatus>({authenticated:false,configured:false,connected:false});const[counts,setCounts]=useState({tasks:0,receivables:0,activity:0,notes:0});const[dnd,setDnd]=useState<DndBlock[]>([]);const[dndLabel,setDndLabel]=useState("Deep Work");const[dndStart,setDndStart]=useState("09:00");const[dndEnd,setDndEnd]=useState("11:00");const[userSettings,setUserSettings]=useState<Record<string,unknown>>({});const[backupFiles,setBackupFiles]=useState<BackupFile[]>([]);const[homeWidgets,setHomeWidgets]=useState<string[]>(HOME_WIDGETS.map(x=>x[0]));const[lifeScoreEnabled,setLifeScoreEnabled]=useState(true);const[birthDate,setBirthDate]=useState("1992-02-25");const[retirementAge,setRetirementAge]=useState(40);const[oneYearGoal,setOneYearGoal]=useState("");const[fiveYearGoal,setFiveYearGoal]=useState("");

 useEffect(()=>{(async()=>{try{
   const saved=(localStorage.getItem("lifeos_theme") as "dark"|"light"|null)||"dark";setTheme(saved);
   const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx)return;setUserId(ctx.user.id);
   const[p,n,t,r,a,s,g,d,u,b]=await Promise.all([
     sb.from("profiles").select("timezone,currency,daily_focus_target,weekly_focus_target").eq("id",ctx.user.id).maybeSingle(),
     sb.from("notification_preferences").select("quiet_start,quiet_end,allow_critical_in_quiet").eq("user_id",ctx.user.id).maybeSingle(),
     sb.from("tasks").select("id",{count:"exact",head:true}).eq("workspace_id",ctx.workspaceId),
     sb.from("receivables").select("id",{count:"exact",head:true}).eq("workspace_id",ctx.workspaceId),
     sb.from("activity_log").select("id",{count:"exact",head:true}).eq("workspace_id",ctx.workspaceId),
     sb.from("sticky_notes").select("id",{count:"exact",head:true}).eq("workspace_id",ctx.workspaceId),
     fetch("/api/integrations/google-calendar/status",{cache:"no-store"}).then(x=>x.json()).catch(()=>({authenticated:true,configured:false,connected:false})),
     sb.from("notification_dnd_blocks").select("id,label,start_time,end_time,days_of_week,active").eq("user_id",ctx.user.id).order("created_at"),
     sb.from("user_settings").select("settings").eq("user_id",ctx.user.id).maybeSingle(),
     fetch("/api/backups/list",{cache:"no-store"}).then(x=>x.ok?x.json():({backups:[]})).catch(()=>({backups:[]}))
   ]);
   if(p.data){setTimezone(p.data.timezone||"Asia/Dubai");setCurrency(p.data.currency||"AED");setDailyFocus(Number(p.data.daily_focus_target||120));setWeeklyFocus(Number(p.data.weekly_focus_target||600));}
   if(n.data){setQuietStart(n.data.quiet_start||"22:30");setQuietEnd(n.data.quiet_end||"07:00");setAllowCritical(Boolean(n.data.allow_critical_in_quiet));}
   if(d.error)throw d.error;if(u.error)throw u.error;const us=(u.data?.settings||{}) as Record<string,unknown>;setUserSettings(us);setBirthDate(typeof us.birth_date==="string"?us.birth_date:"1992-02-25");setRetirementAge(Number.isFinite(Number(us.retirement_age))?Number(us.retirement_age):40);setOneYearGoal(typeof us.one_year_goal==="string"?us.one_year_goal:"");setFiveYearGoal(typeof us.five_year_goal==="string"?us.five_year_goal:"");if(us.theme==="dark"||us.theme==="light"){setTheme(us.theme);localStorage.setItem("lifeos_theme",us.theme);document.documentElement.dataset.theme=us.theme;}const savedWidgets=Array.isArray(us.home_widgets)?us.home_widgets.map(String):HOME_WIDGETS.map(x=>x[0]);setHomeWidgets(savedWidgets);setLifeScoreEnabled(us.life_score_enabled!==false);setCounts({tasks:t.count||0,receivables:r.count||0,activity:a.count||0,notes:s.count||0});setGoogle(g as GoogleStatus);setDnd((d.data||[]) as DndBlock[]);setBackupFiles(Array.isArray((b as any).backups)?(b as any).backups:[]);
 }catch(e){setError(e instanceof Error?e.message:"Could not load settings");}})();},[]);

 async function applyTheme(next:"dark"|"light"){setTheme(next);localStorage.setItem("lifeos_theme",next);document.documentElement.dataset.theme=next;if(!userId)return;const sb=supabaseBrowser();const settings={...userSettings,theme:next};const q=await sb.from("user_settings").upsert({user_id:userId,settings,updated_at:new Date().toISOString()},{onConflict:"user_id"});if(q.error)setError(q.error.message);else setUserSettings(settings);}

 async function saveProfile(){if(!userId)return;setError("");const sb=supabaseBrowser();const[p,n]=await Promise.all([sb.from("profiles").update({timezone,currency,daily_focus_target:dailyFocus,weekly_focus_target:weeklyFocus,updated_at:new Date().toISOString()}).eq("id",userId),sb.from("notification_preferences").upsert({user_id:userId,quiet_start:quietStart,quiet_end:quietEnd,allow_critical_in_quiet:allowCritical},{onConflict:"user_id"})]);if(p.error||n.error)setError(p.error?.message||n.error?.message||"Save failed");else setMsg("Settings saved.");}

 async function onFile(file:File){setError("");setResult(null);try{const data=JSON.parse(await file.text()) as Record<string,unknown>;const p=previewLegacyImport(data);setBackup(data);setPreview(`Tasks: ${p.counts.tasks}, Habits: ${p.counts.habits}, Goals: ${p.counts.goals}, Receivables: ${p.counts.receivables}, Family tasks: ${p.counts.familyTasks}, Health: ${p.counts.healthEntries}, Hair photos: ${p.counts.hairPhotos}\n`+(p.warnings.join("\n")||"No preview warnings."));}catch(e){setBackup(null);setPreview("");setError(e instanceof Error?e.message:"Could not read backup");}}
 async function importNow(){if(!backup||!confirm("Import this backup into your current LifeOS workspace? Existing matching records will be skipped."))return;setLoading(true);setError("");try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx)throw new Error("Sign in before importing.");setResult(await commitLegacyImport({sb,data:backup as Record<string,any>,workspaceId:ctx.workspaceId,userId:ctx.user.id}));}catch(e){setError(e instanceof Error?e.message:"Import failed");}finally{setLoading(false);}}

 async function exportJSON(){setLoading(true);setError("");try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx)throw new Error("Sign in first.");const tables=["goals","projects","tasks","habits","focus_sessions","health_entries","lab_results","hair_photos","urge_logs","receivables","money_expenses","health_routines","health_routine_logs","water_logs","diet_plan_items","sleep_sessions","time_entries","morning_checkins","family_members","family_tasks","baby_records","migration_countries","migration_documents","calendar_items","journal_entries","daily_reviews","weekly_reviews","monthly_reviews","automation_rules","notifications","sticky_notes"];const out:Record<string,unknown>={exported_at:new Date().toISOString(),workspace_id:ctx.workspaceId};for(const table of tables){const q=await sb.from(table).select("*").eq("workspace_id",ctx.workspaceId);if(q.error)throw new Error(`${table}: ${q.error.message}`);out[table]=q.data||[];}const recIds=((out.receivables||[]) as any[]).map(r=>r.id);if(recIds.length){for(const table of["receivable_payments","receivable_followups"]){const q=await sb.from(table).select("*").in("receivable_id",recIds);if(q.error)throw q.error;out[table]=q.data||[];}}const habitIds=((out.habits||[]) as any[]).map(h=>h.id);if(habitIds.length){const q=await sb.from("habit_logs").select("*").in("habit_id",habitIds);if(q.error)throw q.error;out.habit_logs=q.data||[];}download(`lifeos-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(out,null,2),"application/json");setMsg("JSON backup exported.");}catch(e){setError(e instanceof Error?e.message:"Export failed");}finally{setLoading(false);}}

 async function backupNow(){setLoading(true);setError("");try{const r=await fetch("/api/backups/create",{method:"POST"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Backup failed");const l=await fetch("/api/backups/list",{cache:"no-store"});const d=await l.json();setBackupFiles(Array.isArray(d.backups)?d.backups:[]);setMsg("Private backup created.");}catch(e){setError(e instanceof Error?e.message:"Backup failed");}finally{setLoading(false);}}
 async function exportHealth(){setLoading(true);setError("");try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx)throw new Error("Sign in first.");const tables=["health_entries","health_documents","lab_results","hair_photos","urge_logs","health_routines","health_routine_logs","water_logs","diet_plan_items","sleep_sessions"];const out:Record<string,unknown>={exported_at:new Date().toISOString(),scope:"health"};for(const table of tables){const q=await sb.from(table).select("*").eq("workspace_id",ctx.workspaceId);if(q.error)throw new Error(table+": "+q.error.message);out[table]=q.data||[];}download("lifeos-health-"+new Date().toISOString().slice(0,10)+".json",JSON.stringify(out,null,2),"application/json");setMsg("Health export created.");}catch(e){setError(e instanceof Error?e.message:"Health export failed");}finally{setLoading(false);}}
 async function exportFinance(){setLoading(true);setError("");try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx)throw new Error("Sign in first.");const out:Record<string,unknown>={exported_at:new Date().toISOString(),scope:"finance"};const r=await sb.from("receivables").select("*,receivable_payments(*),receivable_followups(*)").eq("workspace_id",ctx.workspaceId);const e=await sb.from("money_expenses").select("*").eq("workspace_id",ctx.workspaceId);if(r.error)throw r.error;if(e.error)throw e.error;out.receivables=r.data||[];out.money_expenses=e.data||[];download("lifeos-finance-"+new Date().toISOString().slice(0,10)+".json",JSON.stringify(out,null,2),"application/json");setMsg("Finance export created.");}catch(e){setError(e instanceof Error?e.message:"Finance export failed");}finally{setLoading(false);}}
 async function exportCSV(){setLoading(true);setError("");try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx)throw new Error("Sign in first.");const[t,r,e]=await Promise.all([sb.from("tasks").select("name,area,status,importance,deadline,financial_value,waiting_for").eq("workspace_id",ctx.workspaceId),sb.from("receivables").select("name,company,total,due_date,next_followup,status").eq("workspace_id",ctx.workspaceId),sb.from("money_expenses").select("date,amount,category,merchant,is_waste,waste_reason,avoid_next_time").eq("workspace_id",ctx.workspaceId)]);if(t.error)throw t.error;if(r.error)throw r.error;if(e.error)throw e.error;let csv="TYPE,NAME,AREA_COMPANY,STATUS,DATE,VALUE,WAITING_NEXT\n";for(const x of t.data||[])csv+=["Task",x.name,x.area,x.status,x.deadline,x.financial_value,x.waiting_for].map(csvCell).join(",")+"\n";for(const x of r.data||[])csv+=["Receivable",x.name,x.company,x.status,x.due_date,x.total,x.next_followup].map(csvCell).join(",")+"\n";for(const x of e.data||[])csv+=["Expense",x.merchant||x.category,x.category,x.is_waste?"Waste":"Useful",x.date,x.amount,x.avoid_next_time||x.waste_reason].map(csvCell).join(",")+"\n";download(`lifeos-export-${new Date().toISOString().slice(0,10)}.csv`,csv,"text/csv");setMsg("CSV export created.");}catch(e){setError(e instanceof Error?e.message:"CSV export failed");}finally{setLoading(false);}}

 function toggleHomeWidget(key:string){setHomeWidgets(v=>v.includes(key)?v.filter(x=>x!==key):[...v,key]);}
 async function saveHomeWidgets(){if(!userId)return;const sb=supabaseBrowser();const settings={...userSettings,home_widgets:homeWidgets,life_score_enabled:lifeScoreEnabled};const q=await sb.from("user_settings").upsert({user_id:userId,settings,updated_at:new Date().toISOString()},{onConflict:"user_id"});if(q.error)setError(q.error.message);else{setUserSettings(settings);setMsg("Home widgets saved across devices.");}}
 async function saveLifePlan(){if(!userId)return;setError("");const age=Math.max(35,Math.min(80,Math.round(retirementAge||40)));const settings={...userSettings,birth_date:birthDate,retirement_age:age,one_year_goal:oneYearGoal.trim(),five_year_goal:fiveYearGoal.trim()};const sb=supabaseBrowser();const q=await sb.from("user_settings").upsert({user_id:userId,settings,updated_at:new Date().toISOString()},{onConflict:"user_id"});if(q.error)setError(q.error.message);else{setRetirementAge(age);setUserSettings(settings);setMsg("Life clock and long-term plan saved across devices.");}}
 async function addDnd(){if(!userId||!dndLabel.trim())return;setError("");const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx)return;const q=await sb.from("notification_dnd_blocks").insert({workspace_id:ctx.workspaceId,user_id:userId,label:dndLabel.trim(),start_time:dndStart,end_time:dndEnd,days_of_week:[1,2,3,4,5,6,7],active:true});if(q.error)setError(q.error.message);else{const r=await sb.from("notification_dnd_blocks").select("id,label,start_time,end_time,days_of_week,active").eq("user_id",userId).order("created_at");setDnd((r.data||[]) as DndBlock[]);}}
 async function toggleDnd(b:DndBlock){const sb=supabaseBrowser();const q=await sb.from("notification_dnd_blocks").update({active:!b.active,updated_at:new Date().toISOString()}).eq("id",b.id);if(q.error)setError(q.error.message);else setDnd(v=>v.map(x=>x.id===b.id?{...x,active:!x.active}:x));}
 async function removeDnd(id:string){if(!confirm("Delete this Do Not Disturb block?"))return;const sb=supabaseBrowser();const q=await sb.from("notification_dnd_blocks").delete().eq("id",id);if(q.error)setError(q.error.message);else setDnd(v=>v.filter(x=>x.id!==id));}
 async function signOut(){await supabaseBrowser().auth.signOut();location.href="/login";}

 const inserted=result?Object.values(result.inserted).reduce((a,b)=>a+b,0):0;const skipped=result?Object.values(result.skipped).reduce((a,b)=>a+b,0):0;

 return <main className="page-root">
  <div className="section-heading"><div><span className="label">SETTINGS & BACKUP</span><h2>Control the system</h2></div><button onClick={signOut} className="ghost-btn">Sign out</button></div>
  {error&&<p className="mb-4 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}
  {msg&&<p className="mb-4 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-3 text-sm text-emerald-200">{msg}</p>}

  <div className="settings-grid">
   <section className="panel settings-section"><h3>Appearance</h3><p className="small-copy">LifeOS now supports both dark and light mode.</p><div className="section-actions mt"><button onClick={()=>applyTheme("dark")} className={theme==="dark"?"primary-btn":"ghost-btn"}>Dark</button><button onClick={()=>applyTheme("light")} className={theme==="light"?"primary-btn":"ghost-btn"}>Light</button></div></section>

   <section id="life-plan" className="panel settings-section"><h3>Life clock & retirement plan</h3><p className="small-copy">These values power the age counter, retirement-by-40 countdown and 1-year / 5-year direction on Home.</p><div className="settings-row"><span>Date of birth</span><input type="date" value={birthDate} onChange={e=>setBirthDate(e.target.value)}/></div><div className="settings-row"><span>Retirement target age</span><input type="number" min="35" max="80" value={retirementAge} onChange={e=>setRetirementAge(Number(e.target.value)||40)}/></div><label className="mt block text-xs text-slate-400">1-year goal<textarea value={oneYearGoal} onChange={e=>setOneYearGoal(e.target.value)} rows={3} placeholder="The most important result to achieve in the next 12 months." className="mt-1 w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/></label><label className="mt block text-xs text-slate-400">5-year goal<textarea value={fiveYearGoal} onChange={e=>setFiveYearGoal(e.target.value)} rows={3} placeholder="What should life, work and finances look like five years from now?" className="mt-1 w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/></label><button onClick={saveLifePlan} className="primary-btn mt">Save life plan</button></section>

   <section className="panel settings-section"><h3>Home dashboard widgets</h3><p className="small-copy">Choose what stays visible on your command center.</p><div className="grid grid-cols-2 gap-2 mt">{HOME_WIDGETS.map(([key,label])=><label key={key} className="flex items-center gap-2 rounded-lg border border-white/10 p-2 text-xs"><input type="checkbox" checked={homeWidgets.includes(key)} onChange={()=>toggleHomeWidget(key)}/>{label}</label>)}</div><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={lifeScoreEnabled} onChange={e=>setLifeScoreEnabled(e.target.checked)}/>Show optional Life Score</label><button onClick={saveHomeWidgets} className="primary-btn mt">Save dashboard preferences</button></section><section id="google-calendar" className="panel settings-section"><h3>Google Calendar</h3><p className="small-copy">{google.connected?`Connected: ${google.accountEmail||"Google account"}`:google.configured?"OAuth is configured. Connect your Gmail calendar.":"Calendar sync code is installed. Google OAuth server credentials still need to be added in Vercel."}</p><div className="section-actions mt">{google.connected?<><Link href="/calendar" className="primary-btn">Open synced calendar</Link><Link href="/api/integrations/google-calendar/connect?next=/calendar" className="ghost-btn">Reconnect</Link></>:google.configured?<Link href="/api/integrations/google-calendar/connect?next=/calendar" className="primary-btn">Connect Google Calendar</Link>:<span className="pill amber">Configuration required</span>}</div></section>

   <section className="panel settings-section"><h3>Focus & notifications</h3><div className="settings-row"><span>Timezone</span><input value={timezone} onChange={e=>setTimezone(e.target.value)}/></div><div className="settings-row"><span>Currency</span><input value={currency} onChange={e=>setCurrency(e.target.value)}/></div><div className="settings-row"><span>Daily deep work target</span><input type="number" min="15" value={dailyFocus} onChange={e=>setDailyFocus(Number(e.target.value)||15)}/></div><div className="settings-row"><span>Weekly focus target</span><input type="number" min="60" value={weeklyFocus} onChange={e=>setWeeklyFocus(Number(e.target.value)||60)}/></div><div className="settings-row"><span>Quiet hours start</span><input type="time" value={quietStart} onChange={e=>setQuietStart(e.target.value)}/></div><div className="settings-row"><span>Quiet hours end</span><input type="time" value={quietEnd} onChange={e=>setQuietEnd(e.target.value)}/></div><label className="settings-row"><span>Critical alerts in quiet hours</span><input type="checkbox" checked={allowCritical} onChange={e=>setAllowCritical(e.target.checked)}/></label><button onClick={saveProfile} className="primary-btn mt">Save settings</button></section><section className="panel settings-section"><h3>Do Not Disturb intelligence</h3><p className="small-copy">Use blocks for sleep, family time or deep work. Critical alerts can still pass only when you allow them above.</p><div className="grid grid-cols-3 gap-2 mt"><input value={dndLabel} onChange={e=>setDndLabel(e.target.value)} placeholder="Label"/><input type="time" value={dndStart} onChange={e=>setDndStart(e.target.value)}/><input type="time" value={dndEnd} onChange={e=>setDndEnd(e.target.value)}/></div><button type="button" onClick={addDnd} className="primary-btn mt">Add DND block</button><div className="list-stack mt">{dnd.map(b=><div key={b.id} className="priority-item"><span className="priority-number">☾</span><div><strong>{b.label}</strong><small>{b.start_time} → {b.end_time} · {b.active?"Active":"Paused"}</small></div><div className="flex gap-1"><button onClick={()=>toggleDnd(b)} className="mini-btn">{b.active?"Pause":"Enable"}</button><button onClick={()=>removeDnd(b.id)} className="mini-btn text-red-300">Delete</button></div></div>)}</div></section>

   <section className="panel settings-section"><h3>Privacy & important notes</h3><p className="small-copy">PIN/device privacy lives in Privacy. Sticky Notes are cloud-synced and intentionally have no permanent delete permission.</p><div className="section-actions mt"><Link href="/privacy" className="ghost-btn">Privacy / PIN</Link><Link href="/sticky-notes" className="primary-btn">Sticky Notes</Link><Link href="/notifications" className="ghost-btn">Push alerts</Link></div></section>

   <section className="panel settings-section"><h3>Backup & portability</h3><p className="small-copy">Daily private backup runs with the production daily cron. You can also create one now. Manual JSON/CSV exports remain yours to download.</p><div className="section-actions"><button onClick={backupNow} disabled={loading} className="primary-btn">Backup now</button><button onClick={exportJSON} disabled={loading} className="ghost-btn">Export JSON</button><button onClick={exportCSV} disabled={loading} className="ghost-btn">Export CSV</button><button onClick={exportHealth} disabled={loading} className="ghost-btn">Health JSON</button><button onClick={exportFinance} disabled={loading} className="ghost-btn">Finance JSON</button><button onClick={()=>window.print()} className="ghost-btn">Print / Save PDF</button><button onClick={()=>document.getElementById("legacy-import")?.scrollIntoView({behavior:"smooth"})} className="ghost-btn">Import JSON</button></div><div className="list-stack mt">{backupFiles.slice(0,7).map(b=><a key={b.name} href={"/api/backups/download?name="+encodeURIComponent(b.name)} className="priority-item"><span className="priority-number">B</span><div><strong>{b.name}</strong><small>{b.updated_at?new Date(b.updated_at).toLocaleString():"Private Supabase backup"}</small></div><span className="pill blue">Download</span></a>)}{backupFiles.length===0&&<p className="small-copy">No automatic backup file yet. Use Backup now to create the first one.</p>}</div></section>

   <section className="panel settings-section"><h3>Maintenance</h3><div className="settings-row"><span>Tasks</span><b>{counts.tasks}</b></div><div className="settings-row"><span>Receivables</span><b>{counts.receivables}</b></div><div className="settings-row"><span>Sticky notes</span><b>{counts.notes}</b></div><div className="settings-row"><span>Activity log</span><b>{counts.activity}</b></div><div className="section-actions mt"><Link href="/timeline" className="ghost-btn">View activity</Link><Link href="/progress" className="ghost-btn">Progress</Link></div></section>
  </div>

  <section className="panel mt"><div className="panel-head"><div><span className="label">ALL LIFEOS OPTIONS</span><h3>Feature directory</h3></div><span className="pill blue">{featureLinks.length} modules</span></div><div className="feature-directory">{featureLinks.map(([name,href])=><Link key={href} href={href} className="feature-link">{name}<span>→</span></Link>)}</div></section>

  <section id="legacy-import" className="panel mt"><div className="panel-head"><div><span className="label">RESTORE</span><h3>Import old standalone backup</h3></div></div><input type="file" accept="application/json,.json" onChange={e=>e.target.files?.[0]&&onFile(e.target.files[0])}/><pre className="mt whitespace-pre-wrap text-xs text-slate-300">{preview||"Choose a lifeos-backup-*.json file to preview."}</pre>{backup&&<button onClick={importNow} disabled={loading} className="primary-btn mt">{loading?"Working…":"Confirm cloud import"}</button>}</section>

  {result&&<section className="panel mt"><h3>Import complete</h3><p className="small-copy">{inserted} records inserted · {skipped} matching records skipped.</p>{result.warnings.length>0&&<div className="mt rounded-lg border border-amber-300/20 bg-amber-300/10 p-3 text-xs text-amber-100">{result.warnings.map(w=><div key={w}>{w}</div>)}</div>}</section>}
 </main>;
}
