"use client";

import { useEffect,useState } from "react";
import Link from "next/link";
import { previewLegacyImport } from "@/lib/legacy-import";
import { commitLegacyImport,type LegacyImportResult } from "@/lib/legacy-import-commit";
import { supabaseBrowser } from "@/lib/supabase/client";
import { currentWorkspace } from "@/lib/supabase/workspace";

function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
function csvCell(v:unknown){const s=String(v??"");return `"${s.replace(/"/g,'""')}"`;}

export default function SettingsPage(){
 const[preview,setPreview]=useState("");const[backup,setBackup]=useState<Record<string,unknown>|null>(null);const[result,setResult]=useState<LegacyImportResult|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");const[msg,setMsg]=useState("");
 const[timezone,setTimezone]=useState("Asia/Dubai");const[currency,setCurrency]=useState("AED");const[quietStart,setQuietStart]=useState("22:30");const[quietEnd,setQuietEnd]=useState("07:00");const[allowCritical,setAllowCritical]=useState(false);const[userId,setUserId]=useState("");
 useEffect(()=>{(async()=>{try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx)return;setUserId(ctx.user.id);const[p,n]=await Promise.all([sb.from("profiles").select("timezone,currency").eq("id",ctx.user.id).maybeSingle(),sb.from("notification_preferences").select("quiet_start,quiet_end,allow_critical_in_quiet").eq("user_id",ctx.user.id).maybeSingle()]);if(p.data){setTimezone(p.data.timezone||"Asia/Dubai");setCurrency(p.data.currency||"AED");}if(n.data){setQuietStart(n.data.quiet_start||"22:30");setQuietEnd(n.data.quiet_end||"07:00");setAllowCritical(Boolean(n.data.allow_critical_in_quiet));}}catch(e){setError(e instanceof Error?e.message:"Could not load settings");}})();},[]);
 async function saveProfile(){if(!userId)return;setError("");const sb=supabaseBrowser();const[p,n]=await Promise.all([sb.from("profiles").update({timezone,currency,updated_at:new Date().toISOString()}).eq("id",userId),sb.from("notification_preferences").upsert({user_id:userId,quiet_start:quietStart,quiet_end:quietEnd,allow_critical_in_quiet:allowCritical},{onConflict:"user_id"})]);if(p.error||n.error)setError(p.error?.message||n.error?.message||"Save failed");else setMsg("Settings saved.");}
 async function onFile(file:File){setError("");setResult(null);try{const data=JSON.parse(await file.text()) as Record<string,unknown>;const p=previewLegacyImport(data);setBackup(data);setPreview(`Tasks: ${p.counts.tasks}, Habits: ${p.counts.habits}, Goals: ${p.counts.goals}, Receivables: ${p.counts.receivables}, Family tasks: ${p.counts.familyTasks}, Health: ${p.counts.healthEntries}, Hair photos: ${p.counts.hairPhotos}\n`+(p.warnings.join("\n")||"No preview warnings."));}catch(e){setBackup(null);setPreview("");setError(e instanceof Error?e.message:"Could not read backup");}}
 async function importNow(){if(!backup||!confirm("Import this backup into your current LifeOS workspace? Existing matching records will be skipped."))return;setLoading(true);setError("");try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx)throw new Error("Sign in before importing.");setResult(await commitLegacyImport({sb,data:backup as Record<string,any>,workspaceId:ctx.workspaceId,userId:ctx.user.id}));}catch(e){setError(e instanceof Error?e.message:"Import failed");}finally{setLoading(false);}}
 async function exportJSON(){setLoading(true);setError("");try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx)throw new Error("Sign in first.");const tables=["goals","projects","tasks","habits","focus_sessions","health_entries","lab_results","hair_photos","urge_logs","receivables","family_members","family_tasks","baby_records","migration_countries","migration_documents","calendar_items","journal_entries","daily_reviews","weekly_reviews","monthly_reviews","automation_rules","notifications"];const out:Record<string,unknown>={exported_at:new Date().toISOString(),workspace_id:ctx.workspaceId};for(const table of tables){const q=await sb.from(table).select("*").eq("workspace_id",ctx.workspaceId);if(q.error)throw new Error(`${table}: ${q.error.message}`);out[table]=q.data||[];}const recIds=((out.receivables||[]) as any[]).map(r=>r.id);if(recIds.length){for(const table of["receivable_payments","receivable_followups"]){const q=await sb.from(table).select("*").in("receivable_id",recIds);if(q.error)throw q.error;out[table]=q.data||[];}}const habitIds=((out.habits||[]) as any[]).map(h=>h.id);if(habitIds.length){const q=await sb.from("habit_logs").select("*").in("habit_id",habitIds);if(q.error)throw q.error;out.habit_logs=q.data||[];}download(`lifeos-backup-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(out,null,2),"application/json");setMsg("JSON backup exported.");}catch(e){setError(e instanceof Error?e.message:"Export failed");}finally{setLoading(false);}}
 async function exportCSV(){setLoading(true);setError("");try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx)throw new Error("Sign in first.");const[t,r]=await Promise.all([sb.from("tasks").select("name,area,status,importance,deadline,financial_value,waiting_for").eq("workspace_id",ctx.workspaceId),sb.from("receivables").select("name,company,total,due_date,next_followup,status").eq("workspace_id",ctx.workspaceId)]);if(t.error)throw t.error;if(r.error)throw r.error;let csv="TYPE,NAME,AREA_COMPANY,STATUS,DATE,VALUE,WAITING_NEXT\n";for(const x of t.data||[])csv+=["Task",x.name,x.area,x.status,x.deadline,x.financial_value,x.waiting_for].map(csvCell).join(",")+"\n";for(const x of r.data||[])csv+=["Receivable",x.name,x.company,x.status,x.due_date,x.total,x.next_followup].map(csvCell).join(",")+"\n";download(`lifeos-export-${new Date().toISOString().slice(0,10)}.csv`,csv,"text/csv");setMsg("CSV export created.");}catch(e){setError(e instanceof Error?e.message:"CSV export failed");}finally{setLoading(false);}}
 const inserted=result?Object.values(result.inserted).reduce((a,b)=>a+b,0):0;const skipped=result?Object.values(result.skipped).reduce((a,b)=>a+b,0):0;
 return <main className="pt-6"><Link href="/" className="text-sm text-[#8ab6ff]">← Home</Link><p className="mt-2 text-[11px] tracking-widest text-slate-400">SETTINGS</p><h1 className="text-2xl font-bold">Data, reminders & privacy</h1>{error&&<p className="mt-4 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}{msg&&<p className="mt-4 rounded-xl border border-emerald-400/20 bg-emerald-400/10 p-3 text-sm text-emerald-200">{msg}</p>}
 <div className="mt-4 grid gap-4 md:grid-cols-2"><section className="panel p-5"><p className="text-[11px] tracking-widest text-slate-400">PROFILE</p><h2 className="mt-1 text-lg font-bold">Time & reminders</h2><div className="mt-3 grid grid-cols-2 gap-2"><label className="text-xs text-slate-400">Timezone<input value={timezone} onChange={e=>setTimezone(e.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-[#0a1524] p-2 text-white"/></label><label className="text-xs text-slate-400">Currency<input value={currency} onChange={e=>setCurrency(e.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-[#0a1524] p-2 text-white"/></label><label className="text-xs text-slate-400">Quiet start<input type="time" value={quietStart} onChange={e=>setQuietStart(e.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-[#0a1524] p-2 text-white"/></label><label className="text-xs text-slate-400">Quiet end<input type="time" value={quietEnd} onChange={e=>setQuietEnd(e.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-[#0a1524] p-2 text-white"/></label></div><label className="mt-3 flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" checked={allowCritical} onChange={e=>setAllowCritical(e.target.checked)}/>Allow Critical reminders during quiet hours</label><button onClick={saveProfile} className="mt-3 w-full rounded-lg bg-[#77adff] p-2 font-bold text-[#06101f]">Save settings</button><div className="mt-3 flex flex-wrap gap-2"><Link href="/notifications" className="rounded border border-white/10 px-3 py-2 text-sm">Push settings</Link><Link href="/privacy" className="rounded border border-white/10 px-3 py-2 text-sm">Privacy lock</Link></div></section>
 <section className="panel p-5"><p className="text-[11px] tracking-widest text-slate-400">EXPORT</p><h2 className="mt-1 text-lg font-bold">Own your data</h2><p className="mt-2 text-sm text-slate-400">JSON is the full structured backup. CSV is a convenient tasks + receivables export.</p><div className="mt-3 grid grid-cols-2 gap-2"><button onClick={exportJSON} disabled={loading} className="rounded-lg border border-white/10 p-2">Export JSON</button><button onClick={exportCSV} disabled={loading} className="rounded-lg border border-white/10 p-2">Export CSV</button></div><button onClick={()=>window.print()} className="mt-2 w-full rounded-lg border border-white/10 p-2">Print / Save page as PDF</button></section></div>
 <section className="panel mt-4 p-5"><p className="text-[11px] tracking-widest text-slate-400">LEGACY IMPORT</p><h2 className="mt-1 text-lg font-bold">Import old standalone backup</h2><input className="mt-3" type="file" accept="application/json,.json" onChange={e=>e.target.files?.[0]&&onFile(e.target.files[0])}/><pre className="mt-3 whitespace-pre-wrap text-xs text-slate-300">{preview||"Choose a lifeos-backup-*.json file to preview."}</pre>{backup&&<button onClick={importNow} disabled={loading} className="mt-4 rounded-lg bg-[#77adff] px-4 py-2 font-bold text-[#06101f] disabled:opacity-50">{loading?"Working…":"Confirm cloud import"}</button>}</section>
 {result&&<section className="panel mt-4 p-5"><h2 className="font-bold">Import complete</h2><p className="mt-2 text-sm text-slate-300">{inserted} records inserted · {skipped} matching records skipped.</p>{result.warnings.length>0&&<div className="mt-3 rounded-lg border border-amber-300/20 bg-amber-300/10 p-3 text-xs text-amber-100">{result.warnings.map(w=><div key={w}>{w}</div>)}</div>}</section>}
 </main>;
}
