"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { BackHome, Panel } from "@/components/ui";
import { escalation, remaining, type PaymentTx } from "@/lib/money";
import { supabaseBrowser } from "@/lib/supabase/client";
import { currentWorkspace,peekWorkspaceContext } from "@/lib/supabase/workspace";
import { useRealtimeRefresh } from "@/lib/use-realtime-refresh";
import { todayInTZ } from "@/lib/timezone";

type PaymentRow={id:string;amount:number;date:string;method:string|null;note:string|null;created_at:string};
type FollowRow={id:string;date:string;method:string|null;note:string|null;promise_date:string|null;next_followup:string|null;status:string|null;created_at:string};
type DocRow={id:string;path:string;created_at:string;url?:string};
type ReceivableRow={
 id:string;name:string;company:string|null;phone:string|null;whatsapp:string|null;email:string|null;total:number;due_date:string|null;last_followup:string|null;next_followup:string|null;promise_date:string|null;status:string;priority:string|null;notes:string|null;
 receivable_payments:PaymentRow[];receivable_followups:FollowRow[];receivable_documents:DocRow[];
};

function aed(value:number){return new Intl.NumberFormat("en-AE",{style:"currency",currency:"AED",maximumFractionDigits:0}).format(value);}
function daysLate(date:string|null){if(!date)return 0;const today=new Date(todayInTZ()+"T12:00:00").getTime();const due=new Date(date+"T12:00:00").getTime();return Math.max(0,Math.floor((today-due)/86400000));}
function digits(v:string|null){return String(v||"").replace(/\D/g,"");}

export default function MoneyPage(){
 const[rows,setRows]=useState<ReceivableRow[]>([]);const cachedWorkspace=peekWorkspaceContext();const[workspaceId,setWorkspaceId]=useState(cachedWorkspace?.workspaceId||"");const[userId,setUserId]=useState(cachedWorkspace?.user.id||"");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[openId,setOpenId]=useState<string|null>(null);
 const[name,setName]=useState("");const[company,setCompany]=useState("");const[phone,setPhone]=useState("");const[whatsapp,setWhatsapp]=useState("");const[email,setEmail]=useState("");const[total,setTotal]=useState(0);const[dueDate,setDueDate]=useState(todayInTZ());const[nextFollowup,setNextFollowup]=useState(todayInTZ());const[notes,setNotes]=useState("");

 const load=useCallback(async()=>{setLoading(true);setError("");try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx){setWorkspaceId("");setRows([]);return;}setWorkspaceId(ctx.workspaceId);setUserId(ctx.user.id);
  const{data,error:q}=await sb.from("receivables").select("id,name,company,phone,whatsapp,email,total,due_date,last_followup,next_followup,promise_date,status,priority,notes,receivable_payments(id,amount,date,method,note,created_at),receivable_followups(id,date,method,note,promise_date,next_followup,status,created_at),receivable_documents(id,path,created_at)").eq("workspace_id",ctx.workspaceId).order("next_followup",{ascending:true,nullsFirst:false}).limit(200);if(q)throw q;
  const base=(data||[]) as ReceivableRow[];const withUrls=await Promise.all(base.map(async r=>({...r,receivable_documents:await Promise.all((r.receivable_documents||[]).map(async d=>{const{data:s}=await sb.storage.from("lifeos-private").createSignedUrl(d.path,900);return{...d,url:s?.signedUrl};}))})));setRows(withUrls);
 }catch(e){setError(e instanceof Error?e.message:"Could not load receivables");}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);useRealtimeRefresh(["receivables","receivable_payments","receivable_followups"],load,Boolean(workspaceId));

 const calcRemaining=(r:ReceivableRow)=>remaining(Number(r.total||0),(r.receivable_payments||[]).map(p=>({amount:Number(p.amount),date:p.date} satisfies PaymentTx)));
 const stats=useMemo(()=>{const today=todayInTZ();const seven=new Date(today+"T12:00:00");seven.setDate(seven.getDate()+7);const weekEnd=seven.toISOString().slice(0,10);let open=0,overdue=0,dueWeek=0,monthReceived=0;const month=today.slice(0,7);rows.forEach(r=>{const rem=calcRemaining(r);open+=rem;if(rem>0&&r.due_date&&r.due_date<today)overdue+=rem;if(rem>0&&r.due_date&&r.due_date>=today&&r.due_date<=weekEnd)dueWeek+=rem;(r.receivable_payments||[]).forEach(p=>{if(p.date?.startsWith(month))monthReceived+=Number(p.amount||0);});});return{open,overdue,dueWeek,monthReceived};},[rows]);

 async function addReceivable(e:FormEvent){e.preventDefault();if(!workspaceId||!userId||!name.trim()||total<=0)return;const sb=supabaseBrowser();const{error:q}=await sb.from("receivables").insert({workspace_id:workspaceId,created_by:userId,name:name.trim(),company:company.trim()||null,phone:phone.trim()||null,whatsapp:whatsapp.trim()||null,email:email.trim()||null,total,due_date:dueDate||null,next_followup:nextFollowup||null,status:"Due",priority:"Normal",notes:notes.trim()||null});if(q)setError(q.message);else{setName("");setCompany("");setPhone("");setWhatsapp("");setEmail("");setTotal(0);setNotes("");await load();}}

 async function recordPayment(r:ReceivableRow){const rem=calcRemaining(r);const raw=prompt(`Payment from ${r.name}. Remaining ${aed(rem)}. Amount:`);if(!raw)return;const amount=Number(raw);if(!Number.isFinite(amount)||amount<=0||amount>rem){setError("Payment must be greater than 0 and cannot exceed remaining balance.");return;}const method=prompt("Method: Cash / Card / Bank / Cheque / Other","Bank")||"Other";const reference=prompt("Reference or note (optional)","")||"";const sb=supabaseBrowser();const{error:q}=await sb.from("receivable_payments").insert({receivable_id:r.id,amount,date:todayInTZ(),method,note:reference||null,created_by:userId});if(q){setError(q.message);return;}const newRemaining=rem-amount;const u=await sb.from("receivables").update({status:newRemaining<=0?"Paid":"Partially Paid",updated_at:new Date().toISOString()}).eq("id",r.id);if(u.error)setError(u.error.message);else await load();}

 async function editReceivable(r:ReceivableRow){const person=prompt("Person / account name",r.name);if(!person?.trim())return;const company=prompt("Company",r.company||"");if(company==null)return;const due=prompt("Original due date (YYYY-MM-DD)",r.due_date||"");if(due==null)return;const next=prompt("Next follow-up (YYYY-MM-DD)",r.next_followup||"");if(next==null)return;const notes=prompt("Notes",r.notes||"");if(notes==null)return;const sb=supabaseBrowser();const q=await sb.from("receivables").update({name:person.trim(),company:company.trim()||null,due_date:due||null,next_followup:next||null,notes:notes.trim()||null,updated_at:new Date().toISOString()}).eq("id",r.id);if(q.error)setError(q.error.message);else await load();}
 async function removeReceivable(r:ReceivableRow){if(!confirm(`Delete receivable "${r.name}" and its follow-up/payment history?`))return;const sb=supabaseBrowser();const q=await sb.from("receivables").delete().eq("id",r.id);if(q.error)setError(q.error.message);else await load();}
 async function addFollowup(r:ReceivableRow){const note=prompt(`Follow-up note for ${r.name}:`);if(!note?.trim())return;const method=prompt("Method: Call / WhatsApp / Email / Meeting","Call")||"Call";const promise=prompt("Promise date (YYYY-MM-DD, optional):",r.promise_date||"")||"";const next=prompt("Next follow-up date (YYYY-MM-DD):",r.next_followup||todayInTZ())||r.next_followup||todayInTZ();const sb=supabaseBrowser();const{error:q}=await sb.from("receivable_followups").insert({receivable_id:r.id,date:todayInTZ(),method,note:note.trim(),promise_date:promise||null,next_followup:next,status:promise?"Promised":"Follow-up",created_by:userId});if(q){setError(q.message);return;}const late=daysLate(r.due_date);const priority=escalation({overdueDays:late,promiseMissed:Boolean(r.promise_date&&r.promise_date<todayInTZ()&&calcRemaining(r)>0)});const u=await sb.from("receivables").update({last_followup:todayInTZ(),next_followup:next,promise_date:promise||r.promise_date,status:promise?"Promised":"Follow-up",priority,updated_at:new Date().toISOString()}).eq("id",r.id);if(u.error)setError(u.error.message);else await load();}

 async function uploadEvidence(r:ReceivableRow,file:File){try{if(file.size>15*1024*1024)throw new Error("Attachment must be under 15 MB.");const sb=supabaseBrowser();const id=crypto.randomUUID();const ext=(file.name.split(".").pop()||"bin").replace(/[^a-z0-9]/gi,"");const path=`${workspaceId}/${userId}/money/${r.id}/${id}.${ext}`;const up=await sb.storage.from("lifeos-private").upload(path,file,{contentType:file.type||"application/octet-stream"});if(up.error)throw up.error;const ins=await sb.from("receivable_documents").insert({id,receivable_id:r.id,path,created_by:userId});if(ins.error){await sb.storage.from("lifeos-private").remove([path]);throw ins.error;}await load();}catch(e){setError(e instanceof Error?e.message:"Attachment upload failed");}}
 async function removeEvidence(r:ReceivableRow,d:DocRow){if(!confirm("Delete this evidence file?"))return;const sb=supabaseBrowser();const q=await sb.from("receivable_documents").delete().eq("id",d.id);if(q.error){setError(q.error.message);return;}await sb.storage.from("lifeos-private").remove([d.path]);await load();}

 return <main className="pt-6"><BackHome/><div className="mt-2 flex flex-wrap items-end justify-between gap-3"><div><p className="text-[11px] tracking-widest text-slate-400">MONEY RECOVERY CRM</p><h1 className="text-2xl font-bold">Receivables</h1></div><Link href="/expenses" className="ghost-btn">Waste Guard →</Link></div>{error&&<p className="mt-3 rounded-xl border border-red-400/20 bg-red-400/10 p-3 text-sm text-red-200">{error}</p>}
 {!loading&&!workspaceId?<p className="panel mt-4 p-5 text-sm">Sign in first. <Link href="/login" className="text-[#8ab6ff]">Login →</Link></p>:<>
 <div className="mt-4 grid gap-4 md:grid-cols-4">{[["Total receivable",aed(stats.open)],["Received this month",aed(stats.monthReceived)],["Overdue",aed(stats.overdue)],["Due this week",aed(stats.dueWeek)]].map(([t,v])=><div key={t} className="panel p-4"><span className="text-xs text-slate-400">{t}</span><strong className="mt-2 block text-xl">{v}</strong></div>)}</div>
 <div className="mt-4 grid gap-4 md:grid-cols-[.7fr_1.3fr]"><Panel title="Add receivable" kicker="NEW"><form onSubmit={addReceivable} className="space-y-2"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Person" className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><input value={company} onChange={e=>setCompany(e.target.value)} placeholder="Company" className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><div className="grid grid-cols-2 gap-2"><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone" className="rounded-lg border border-white/10 bg-[#0a1524] p-2"/><input value={whatsapp} onChange={e=>setWhatsapp(e.target.value)} placeholder="WhatsApp" className="rounded-lg border border-white/10 bg-[#0a1524] p-2"/></div><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email" className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><input required type="number" min="1" value={total||""} onChange={e=>setTotal(Number(e.target.value))} placeholder="Total AED" className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><div className="grid grid-cols-2 gap-2"><label className="text-xs text-slate-400">Due date<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-[#0a1524] p-2 text-white"/></label><label className="text-xs text-slate-400">Next follow-up<input type="date" value={nextFollowup} onChange={e=>setNextFollowup(e.target.value)} className="mt-1 w-full rounded-lg border border-white/10 bg-[#0a1524] p-2 text-white"/></label></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Notes" className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><button className="w-full rounded-lg bg-[#77adff] p-2 font-bold text-[#06101f]">Save receivable</button></form></Panel>
 <Panel title={loading?"Loading…":"Follow-up queue"}><div className="space-y-2">{rows.length===0&&!loading&&<p className="text-sm text-slate-400">No receivables yet.</p>}{rows.map(r=>{const rem=calcRemaining(r);const late=daysLate(r.due_date);const promiseMissed=Boolean(r.promise_date&&r.promise_date<todayInTZ()&&rem>0);const level=escalation({overdueDays:late,promiseMissed});const open=openId===r.id;return <div key={r.id} className="rounded-xl border border-white/10 p-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><strong>{r.name}</strong><span className={`rounded-full px-2 py-0.5 text-[10px] ${level==="Critical"?"bg-red-400/15 text-red-200":level==="High"?"bg-amber-300/15 text-amber-100":level==="Important"?"bg-blue-300/15 text-blue-100":"bg-white/5 text-slate-400"}`}>{level}</span>{promiseMissed&&<span className="text-[10px] text-red-300">PROMISE MISSED</span>}</div><p className="text-xs text-slate-400">{r.company?`${r.company} · `:""}{aed(rem)} remaining of {aed(Number(r.total))} · due {r.due_date||"—"}{late?` · ${late}d overdue`:""} · next {r.next_followup||"—"} · {rem<=0?"Paid":r.status}</p><div className="mt-1 flex gap-3 text-xs">{digits(r.whatsapp)&&<a className="text-[#9fc4ff]" target="_blank" rel="noreferrer" href={`https://wa.me/${digits(r.whatsapp)}`}>WhatsApp</a>}{r.email&&<a className="text-[#9fc4ff]" href={`mailto:${r.email}`}>Email</a>}{r.phone&&<span className="text-slate-500">{r.phone}</span>}</div></div><div className="flex flex-wrap gap-2">{rem>0&&<button onClick={()=>recordPayment(r)} className="rounded-lg border border-white/10 px-2 py-1 text-xs">Payment</button>}{rem>0&&<button onClick={()=>addFollowup(r)} className="rounded-lg border border-white/10 px-2 py-1 text-xs">Follow up</button>}<button onClick={()=>setOpenId(open?null:r.id)} className="rounded-lg border border-white/10 px-2 py-1 text-xs">{open?"Hide":"History"}</button><button onClick={()=>editReceivable(r)} className="rounded-lg border border-white/10 px-2 py-1 text-xs">Edit</button><button onClick={()=>removeReceivable(r)} className="rounded-lg border border-red-400/20 px-2 py-1 text-xs text-red-300">Delete</button><label className="cursor-pointer rounded-lg border border-white/10 px-2 py-1 text-xs">Attach<input type="file" className="hidden" onChange={e=>{const file=e.target.files?.[0];if(file)void uploadEvidence(r,file);e.currentTarget.value="";}}/></label></div></div>
 {open&&<div className="mt-3 grid gap-3 border-t border-white/10 pt-3 md:grid-cols-2"><div><b className="text-xs uppercase tracking-wider text-slate-500">Follow-ups</b><div className="mt-2 space-y-1">{(r.receivable_followups||[]).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).map(f=><div key={f.id} className="rounded bg-white/[.03] p-2 text-xs"><b>{f.date} · {f.method||"Follow-up"}</b><p>{f.note}</p>{f.promise_date&&<p className="text-amber-200">Promise: {f.promise_date}</p>}</div>)}</div></div><div><b className="text-xs uppercase tracking-wider text-slate-500">Payments & evidence</b><div className="mt-2 space-y-1">{(r.receivable_payments||[]).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).map(p=><div key={p.id} className="rounded bg-white/[.03] p-2 text-xs"><b>{p.date} · {aed(Number(p.amount))}</b><p>{p.method||"Other"}{p.note?` · ${p.note}`:""}</p></div>)}{(r.receivable_documents||[]).map(d=><div key={d.id} className="flex justify-between rounded bg-white/[.03] p-2 text-xs"><span>Evidence · {new Date(d.created_at).toLocaleDateString()}</span><span>{d.url&&<a className="mr-2 text-[#9fc4ff]" href={d.url} target="_blank" rel="noreferrer">Open</a>}<button onClick={()=>removeEvidence(r,d)} className="text-red-300">Delete</button></span></div>)}</div></div></div>}</div>})}</div></Panel></div></>}
 </main>;
}
