"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { BackHome, Panel } from "@/components/ui";
import { supabaseBrowser } from "@/lib/supabase/client";
import { currentWorkspaceId } from "@/lib/supabase/workspace";
type Expense={id:string;date:string;amount:number;category:string;merchant:string|null;note:string|null;is_waste:boolean;waste_reason:string|null};
export default function ExpensesPage(){
 const sb=supabaseBrowser(); const [workspace,setWorkspace]=useState(""); const [items,setItems]=useState<Expense[]>([]); const [msg,setMsg]=useState("Loading…");
 async function load(){try{const ws=await currentWorkspaceId(sb);setWorkspace(ws);const {data,error}=await sb.from("expenses").select("*").eq("workspace_id",ws).order("date",{ascending:false}).limit(100);if(error)throw error;setItems(data||[]);setMsg("");}catch(e){setMsg(e instanceof Error?e.message:"Could not load expenses");}}
 useEffect(()=>{void load();},[]);
 async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {data:u}=await sb.auth.getUser();const waste=f.get("waste")==="on";const {error}=await sb.from("expenses").insert({workspace_id:workspace,date:f.get("date"),amount:Number(f.get("amount")),category:f.get("category"),merchant:f.get("merchant")||null,note:f.get("note")||null,is_waste:waste,waste_reason:waste?(f.get("reason")||"Avoidable spend"):null,created_by:u.user?.id});if(error)setMsg(error.message);else{e.currentTarget.reset();await load();}}
 const month=new Date().toISOString().slice(0,7);const stats=useMemo(()=>{const m=items.filter(x=>x.date.startsWith(month));return {total:m.reduce((a,x)=>a+Number(x.amount),0),waste:m.filter(x=>x.is_waste).reduce((a,x)=>a+Number(x.amount),0)}},[items,month]);
 return <main className="pt-6"><BackHome/><p className="mt-2 text-[11px] tracking-widest text-slate-400">MONEY → SPENDING</p><h1 className="text-2xl font-bold">Expenses & waste guard</h1>{msg&&<p className="notice mt-3">{msg}</p>}
 <div className="mt-4 grid gap-4 md:grid-cols-3"><div className="panel p-5"><small>This month</small><strong className="metric">AED {stats.total.toFixed(0)}</strong></div><div className="panel p-5 waste-card"><small>Waste of money</small><strong className="metric">AED {stats.waste.toFixed(0)}</strong><p className="text-xs">Avoidable spending you chose to remember.</p></div><div className="panel p-5"><small>Useful spend</small><strong className="metric">AED {(stats.total-stats.waste).toFixed(0)}</strong></div></div>
 <div className="mt-4 grid gap-4 md:grid-cols-[.8fr_1.2fr]"><Panel title="Add expense" kicker="INTENTIONAL SPENDING"><form onSubmit={add} className="form-grid"><input name="date" type="date" required defaultValue={new Date().toISOString().slice(0,10)}/><input name="amount" type="number" min="0" step="0.01" placeholder="Amount AED" required/><select name="category"><option>Food</option><option>Shopping</option><option>Transport</option><option>Bills</option><option>Family</option><option>Health</option><option>Business</option><option>Other</option></select><input name="merchant" placeholder="Merchant / place"/><input name="note" placeholder="What was it?"/><label className="check-line"><input name="waste" type="checkbox"/> Waste of money / fazool kharcha</label><input name="reason" placeholder="Why was it avoidable?"/><button disabled={!workspace}>Save expense</button></form></Panel>
 <Panel title="Recent spending" kicker="REMEMBER BEFORE REPEATING"><div className="mini-list">{items.map(x=><span key={x.id} className={x.is_waste?"waste-row":""}><b>{"AED "+Number(x.amount).toFixed(0)+" · "+x.category+(x.is_waste?" · WASTE":"")}</b><small>{x.date+(x.merchant?" · "+x.merchant:"")+(x.waste_reason?" · "+x.waste_reason:"")}</small></span>)}</div></Panel></div></main>;
}