"use client";

import { FormEvent,useCallback,useEffect,useState } from "react";
import Link from "next/link";
import { BackHome,Panel } from "@/components/ui";
import { PrivacyGate } from "@/components/privacy-gate";
import { supabaseBrowser } from "@/lib/supabase/client";
import { currentWorkspace } from "@/lib/supabase/workspace";

type Doc={id:string;title:string;path:string;created_at:string;url?:string};

function VaultContent(){
 const[workspaceId,setWorkspaceId]=useState("");const[userId,setUserId]=useState("");const[rows,setRows]=useState<Doc[]>([]);const[title,setTitle]=useState("");const[file,setFile]=useState<File|null>(null);const[error,setError]=useState("");const[uploading,setUploading]=useState(false);
 const load=useCallback(async()=>{try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx){setWorkspaceId("");return;}setWorkspaceId(ctx.workspaceId);setUserId(ctx.user.id);const{data,error:q}=await sb.from("health_documents").select("id,title,path,created_at").eq("workspace_id",ctx.workspaceId).order("created_at",{ascending:false});if(q)throw q;const docs=(data||[]) as Doc[];const signed=await Promise.all(docs.map(async d=>{const{data:s}=await sb.storage.from("lifeos-private").createSignedUrl(d.path,900);return{...d,url:s?.signedUrl};}));setRows(signed);}catch(e){setError(e instanceof Error?e.message:"Could not load Health Vault");}},[]);useEffect(()=>{void load();},[load]);
 async function upload(e:FormEvent){e.preventDefault();if(!file||!title.trim())return;setUploading(true);setError("");try{if(file.size>15*1024*1024)throw new Error("File must be under 15 MB.");const sb=supabaseBrowser();const id=crypto.randomUUID();const ext=(file.name.split(".").pop()||"bin").replace(/[^a-z0-9]/gi,"");const path=`${workspaceId}/${userId}/health/${id}.${ext}`;const up=await sb.storage.from("lifeos-private").upload(path,file,{contentType:file.type||"application/octet-stream"});if(up.error)throw up.error;const ins=await sb.from("health_documents").insert({id,workspace_id:workspaceId,created_by:userId,title:title.trim(),path,privacy:"private"});if(ins.error){await sb.storage.from("lifeos-private").remove([path]);throw ins.error;}setTitle("");setFile(null);await load();}catch(e){setError(e instanceof Error?e.message:"Upload failed");}finally{setUploading(false);}}
 async function remove(d:Doc){if(!confirm("Delete this health document?"))return;const sb=supabaseBrowser();const q=await sb.from("health_documents").delete().eq("id",d.id);if(q.error){setError(q.error.message);return;}await sb.storage.from("lifeos-private").remove([d.path]);await load();}
 return <main className="pt-6"><BackHome/><p className="mt-2 text-[11px] tracking-widest text-slate-400">HEALTH VAULT</p><h1 className="text-2xl font-bold">Private reports & documents</h1>{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}{!workspaceId?<p className="panel mt-4 p-5 text-sm">Sign in first. <Link href="/login" className="text-[#8ab6ff]">Login →</Link></p>:<div className="mt-4 grid gap-4 md:grid-cols-[.7fr_1.3fr]"><Panel title="Upload"><form onSubmit={upload} className="space-y-2"><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Report / prescription title" className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><input required type="file" onChange={e=>setFile(e.target.files?.[0]||null)} className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><button disabled={uploading} className="w-full rounded-lg bg-[#77adff] p-2 font-bold text-[#06101f] disabled:opacity-50">{uploading?"Uploading…":"Upload privately"}</button></form></Panel><Panel title="Documents">{rows.map(d=><div key={d.id} className="mb-2 flex items-center justify-between gap-3 rounded-lg border border-white/10 p-3"><div><b className="text-sm">{d.title}</b><p className="text-xs text-slate-500">{new Date(d.created_at).toLocaleDateString()}</p></div><div className="flex gap-2">{d.url&&<a href={d.url} target="_blank" rel="noreferrer" className="rounded border border-white/10 px-2 py-1 text-xs">Open</a>}<button onClick={()=>remove(d)} className="text-xs text-red-300">Delete</button></div></div>)}</Panel></div>}</main>;
}

export default function HealthVaultPage(){return <PrivacyGate><VaultContent/></PrivacyGate>;}
