"use client";

import { useCallback,useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { BackHome,Panel } from "@/components/ui";
import { remaining } from "@/lib/money";
import { supabaseBrowser } from "@/lib/supabase/client";
import { currentWorkspace } from "@/lib/supabase/workspace";

type Task={id:string;name:string;status:string;deadline:string|null;importance:number|null;waiting_for:string|null;responsible:string|null;business_section:string|null};
const SECTIONS=["Today Operations","Business Projects","Pending Decisions","Payments","Staff Follow-ups","Government Documents","Renewals","Marketing","CRM Development"];
type Project={id:string;name:string;status:string;deadline:string|null};
type Rec={id:string;name:string;total:number;due_date:string|null;receivable_payments:{amount:number;date:string}[]};

export default function BusinessPage(){
 const[tasks,setTasks]=useState<Task[]>([]);const[projects,setProjects]=useState<Project[]>([]);const[recs,setRecs]=useState<Rec[]>([]);const[signedIn,setSignedIn]=useState<boolean|null>(null);const[error,setError]=useState("");
 const load=useCallback(async()=>{try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx){setSignedIn(false);return;}setSignedIn(true);const[t,p,r]=await Promise.all([sb.from("tasks").select("id,name,status,deadline,importance,waiting_for,responsible,business_section").eq("workspace_id",ctx.workspaceId).eq("area","Business").not("status","in",'("Completed","Cancelled")').limit(100),sb.from("projects").select("id,name,status,deadline").eq("workspace_id",ctx.workspaceId).eq("area","Business").not("status","in",'("Completed","Cancelled")').limit(100),sb.from("receivables").select("id,name,total,due_date,receivable_payments(amount,date)").eq("workspace_id",ctx.workspaceId).neq("status","Paid").limit(100)]);for(const q of[t,p,r])if(q.error)throw q.error;setTasks((t.data||[]) as Task[]);setProjects((p.data||[]) as Project[]);setRecs((r.data||[]) as Rec[]);}catch(e){setError(e instanceof Error?e.message:"Could not load business command center");}},[]);useEffect(()=>{void load();},[load]);
 const openMoney=useMemo(()=>recs.reduce((a,r)=>a+remaining(Number(r.total||0),(r.receivable_payments||[]).map(p=>({amount:Number(p.amount),date:p.date}))),0),[recs]);
 return <main className="page-root"><BackHome/><div className="section-heading"><div><span className="label">BUSINESS COMMAND CENTER</span><h2>Operations that need attention</h2></div><div className="section-actions"><Link href="/tasks" className="ghost-btn">+ Business task</Link><Link href="/projects" className="primary-btn">Projects</Link></div></div>{error&&<p className="mb-4 text-sm text-red-300">{error}</p>}{signedIn===false?<p className="panel p-5 text-sm">Sign in first. <Link href="/login" className="text-btn">Login →</Link></p>:<><div className="grid g4">{[["Open business tasks",tasks.length],["Active projects",projects.length],["Waiting",tasks.filter(t=>t.status==="Waiting"||t.waiting_for).length],["Receivable","AED "+openMoney.toLocaleString()]].map(([k,v])=><div key={String(k)} className="metric-card"><span>{k}</span><strong>{v}</strong></div>)}</div><div className="grid g3 mt">{SECTIONS.map(section=>{const rows=tasks.filter(t=>(t.business_section||"Today Operations")===section);return <Panel key={section} title={section} kicker={rows.length+" OPEN"}><div className="list-stack">{rows.sort((a,b)=>Number(b.importance||0)-Number(a.importance||0)).slice(0,8).map(t=><Link href="/tasks" key={t.id} className="priority-item"><span className="priority-number">▤</span><div><strong>{t.name}</strong><small>{t.status} · due {t.deadline||"—"}{t.responsible?" · "+t.responsible:""}{t.waiting_for?" · waiting for "+t.waiting_for:""}</small></div></Link>)}{!rows.length&&<div className="empty-state"><b>Nothing open</b>No active item in this section.</div>}</div></Panel>})}</div><div className="grid g2 mt"><Panel title="Active business projects">{projects.map(p=><Link href="/projects" key={p.id} className="priority-item"><span className="priority-number">P</span><div><strong>{p.name}</strong><small>{p.status} · due {p.deadline||"—"}</small></div></Link>)}</Panel><Panel title="Money needing recovery">{recs.map(r=><Link href="/money" key={r.id} className="priority-item"><span className="priority-number">₳</span><div><strong>{r.name}</strong><small>Due {r.due_date||"—"} · open balance linked to Money Recovery</small></div></Link>)}</Panel></div></>}</main>;
}