"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { BackHome, Panel } from "@/components/ui";
import { supabaseBrowser } from "@/lib/supabase/client";
import { currentWorkspace } from "@/lib/supabase/workspace";
import { useRealtimeRefresh } from "@/lib/use-realtime-refresh";
import { todayInTZ } from "@/lib/timezone";

type Goal={id:string;name:string;area:string|null;deadline:string|null;status:string;progress:number|null;why:string|null;target:number|null;unit:string|null};
type Milestone={id:string;goal_id:string;title:string;done:boolean};
type GoalTask={id:string;goal_id:string|null;status:string};

export default function GoalsPage(){
 const[workspaceId,setWorkspaceId]=useState("");const[userId,setUserId]=useState("");const[goals,setGoals]=useState<Goal[]>([]);const[milestones,setMilestones]=useState<Milestone[]>([]);const[tasks,setTasks]=useState<GoalTask[]>([]);const[open,setOpen]=useState<string|null>(null);
 const[editingId,setEditingId]=useState<string|null>(null);const[name,setName]=useState("");const[why,setWhy]=useState("");const[area,setArea]=useState("Personal");const[target,setTarget]=useState<number|undefined>(100);const[unit,setUnit]=useState("%");const[deadline,setDeadline]=useState(()=>{const d=new Date(todayInTZ()+"T12:00:00");d.setDate(d.getDate()+90);return d.toISOString().slice(0,10);});const[error,setError]=useState("");

 const load=useCallback(async()=>{try{const sb=supabaseBrowser();const ctx=await currentWorkspace(sb);if(!ctx){setWorkspaceId("");return;}setWorkspaceId(ctx.workspaceId);setUserId(ctx.user.id);const[g,t]=await Promise.all([sb.from("goals").select("id,name,area,deadline,status,progress,why,target,unit").eq("workspace_id",ctx.workspaceId).order("deadline",{ascending:true,nullsFirst:false}),sb.from("tasks").select("id,goal_id,status").eq("workspace_id",ctx.workspaceId).not("goal_id","is",null)]);if(g.error)throw g.error;if(t.error)throw t.error;const rows=(g.data||[]) as Goal[];setGoals(rows);setTasks((t.data||[]) as GoalTask[]);const ids=rows.map(x=>x.id);if(ids.length){const m=await sb.from("goal_milestones").select("id,goal_id,title,done").in("goal_id",ids).order("created_at");if(m.error)throw m.error;setMilestones((m.data||[]) as Milestone[]);}else setMilestones([]);}catch(e){setError(e instanceof Error?e.message:"Could not load goals");}},[]);
 useEffect(()=>{void load();},[load]);useRealtimeRefresh(["goals","goal_milestones","tasks"],load,Boolean(workspaceId));

 const computed=useMemo(()=>new Map(goals.map(g=>{const ms=milestones.filter(m=>m.goal_id===g.id);const linked=tasks.filter(t=>t.goal_id===g.id&&!["Cancelled"].includes(t.status));const p=ms.length?Math.round(ms.filter(m=>m.done).length/ms.length*100):linked.length?Math.round(linked.filter(t=>t.status==="Completed").length/linked.length*100):Number(g.progress||0);return[g.id,p];})),[goals,milestones,tasks]);
 async function add(e:FormEvent){e.preventDefault();if(!workspaceId||!name.trim())return;const sb=supabaseBrowser();const payload={name:name.trim(),why:why.trim()||null,area,target:target??100,unit:unit||"%",deadline,privacy:area==="Health"||area==="Self-control"?"private":"family",updated_at:new Date().toISOString()};const q=editingId?await sb.from("goals").update(payload).eq("id",editingId):await sb.from("goals").insert({...payload,workspace_id:workspaceId,created_by:userId,status:"On Track",progress:0});if(q.error)setError(q.error.message);else{setEditingId(null);setName("");setWhy("");await load();}}
 async function addMilestone(g:Goal){const title=prompt(`Add milestone for ${g.name}:`);if(!title?.trim())return;const sb=supabaseBrowser();const{error:q}=await sb.from("goal_milestones").insert({goal_id:g.id,title:title.trim(),done:false});if(q)setError(q.message);else await load();}
 async function toggleMilestone(m:Milestone){const sb=supabaseBrowser();const next=!m.done;const q=await sb.from("goal_milestones").update({done:next}).eq("id",m.id);if(q.error){setError(q.error.message);return;}const siblings=milestones.filter(x=>x.goal_id===m.goal_id).map(x=>x.id===m.id?{...x,done:next}:x);const progress=siblings.length?Math.round(siblings.filter(x=>x.done).length/siblings.length*100):0;const status=progress>=100?"Completed":progress<30?"At Risk":"On Track";const u=await sb.from("goals").update({progress,status,updated_at:new Date().toISOString()}).eq("id",m.goal_id);if(u.error)setError(u.error.message);else await load();}
 async function manualProgress(g:Goal){if(milestones.some(m=>m.goal_id===g.id)){setError("This goal uses milestone-based progress. Complete milestones instead of manually overriding it.");return;}const raw=prompt("Progress 0–100",String(g.progress||0));if(raw==null)return;const n=Math.max(0,Math.min(100,Number(raw)));if(!Number.isFinite(n))return;const status=n>=100?"Completed":n<30?"At Risk":"On Track";const sb=supabaseBrowser();const{error:q}=await sb.from("goals").update({progress:n,status,updated_at:new Date().toISOString()}).eq("id",g.id);if(q)setError(q.message);else await load();}
 async function setStatus(id:string,status:string){const sb=supabaseBrowser();const{error:q}=await sb.from("goals").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(q)setError(q.message);else await load();}
 function startEdit(g:Goal){setEditingId(g.id);setName(g.name);setWhy(g.why||"");setArea(g.area||"Personal");setTarget(g.target??100);setUnit(g.unit||"%");setDeadline(g.deadline||todayInTZ());window.scrollTo({top:0,behavior:"smooth"});}
 function cancelEdit(){setEditingId(null);setName("");setWhy("");}
 async function removeGoal(g:Goal){if(!confirm(`Delete goal "${g.name}"? Linked tasks/projects will keep working but lose this goal link.`))return;const sb=supabaseBrowser();const{error:q}=await sb.from("goals").delete().eq("id",g.id);if(q)setError(q.message);else await load();}

 return <main className="pt-6"><BackHome/><p className="mt-2 text-[11px] tracking-widest text-slate-400">GOALS</p><h1 className="text-2xl font-bold">Long-term outcomes</h1>{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}
 {!workspaceId?<p className="panel mt-4 p-5 text-sm">Sign in first. <Link href="/login" className="text-[#8ab6ff]">Login →</Link></p>:<div className="mt-4 grid gap-4 md:grid-cols-[.7fr_1.3fr]">
 <Panel title={editingId?"Edit goal":"Add goal"}><form onSubmit={add} className="space-y-2"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Goal" className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><textarea value={why} onChange={e=>setWhy(e.target.value)} placeholder="Why does this matter?" className="w-full rounded-lg border border-white/10 bg-[#0a1524] p-2"/><div className="grid grid-cols-2 gap-2"><select value={area} onChange={e=>setArea(e.target.value)} className="rounded-lg border border-white/10 bg-[#0a1524] p-2">{["Health","Business","Money","Growth","Family","Europe","Personal","Self-control"].map(x=><option key={x}>{x}</option>)}</select><input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)} className="rounded-lg border border-white/10 bg-[#0a1524] p-2"/></div><div className="grid grid-cols-2 gap-2"><input type="number" value={target??""} onChange={e=>setTarget(e.target.value?Number(e.target.value):undefined)} placeholder="Target" className="rounded-lg border border-white/10 bg-[#0a1524] p-2"/><input value={unit} onChange={e=>setUnit(e.target.value)} placeholder="Unit" className="rounded-lg border border-white/10 bg-[#0a1524] p-2"/></div><button className="w-full rounded-lg bg-[#77adff] p-2 font-bold text-[#06101f]">{editingId?"Update goal":"Save goal"}</button>{editingId&&<button type="button" onClick={cancelEdit} className="w-full rounded-lg border border-white/10 p-2">Cancel edit</button>}</form></Panel>
 <Panel title="Goals"><div className="space-y-2">{goals.map(g=>{const p=computed.get(g.id)||0;const ms=milestones.filter(m=>m.goal_id===g.id);const expanded=open===g.id;return <div key={g.id} className="rounded-xl border border-white/10 p-3"><div className="flex flex-wrap justify-between gap-3"><div><b>{g.name}</b><p className="text-xs text-slate-500">{g.area} · due {g.deadline||"—"}{g.target!=null?` · target ${g.target} ${g.unit||""}`:""}</p>{g.why&&<p className="mt-1 text-xs text-slate-400">{g.why}</p>}</div><div className="flex gap-2"><select value={g.status} onChange={e=>setStatus(g.id,e.target.value)} className="rounded-lg border border-white/10 bg-[#0a1524] p-1 text-xs">{["On Track","At Risk","Behind","Paused","Completed"].map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>setOpen(expanded?null:g.id)} className="rounded-lg border border-white/10 px-2 py-1 text-xs">{expanded?"Hide":"Milestones"}</button><button onClick={()=>startEdit(g)} className="rounded-lg border border-white/10 px-2 py-1 text-xs">Edit</button><button onClick={()=>removeGoal(g)} className="rounded-lg border border-red-400/20 px-2 py-1 text-xs text-red-300">Delete</button></div></div><div className="mt-2 h-2 overflow-hidden rounded bg-white/10"><div className="h-full bg-[#77adff]" style={{width:`${p}%`}}/></div><div className="mt-1 flex justify-between text-xs text-slate-400"><span>{p}%</span>{!ms.length&&!tasks.some(t=>t.goal_id===g.id)&&<button onClick={()=>manualProgress(g)}>Manual progress</button>}</div>{expanded&&<div className="mt-3 border-t border-white/10 pt-3"><div className="space-y-1">{ms.map(m=><label key={m.id} className="flex items-center gap-2 rounded bg-white/[.03] p-2 text-sm"><input type="checkbox" checked={m.done} onChange={()=>toggleMilestone(m)}/><span className={m.done?"line-through text-slate-500":""}>{m.title}</span></label>)}</div><button onClick={()=>addMilestone(g)} className="mt-2 rounded-lg border border-white/10 px-3 py-1 text-xs">+ Milestone</button></div>}</div>})}</div></Panel>
 </div>}
 </main>;
}
